### ISSUE TITLE
Push linux/arm64 builds for release candidates 

### ISSUE THREAD

**Issue by 527bd5** [typesense/typesense#1000]
## Description

Proper releases like 0.24.0 have linux/arm64 builds on Docker Hub, but release candidates like 0.25.0.rc25 only have linux/amd64 builds. Building for linux/arm64 also for release candidates would significantly improve the development experience for people using ARM-based CPUs.

**Comment by sashahilton00** [comment]
@kishorenc is this something that you'd be open to doing now that the bazel migration is complete? The amd64 images on newer macs have the unfortunate effect of turning them into space heaters whilst running.

**Comment by jasonbosco** [comment]
We've now started publishing arm64 and amd64 builds for RC candidates since last week, starting from `0.25.0.rc59`. 

You can download DEB, RPM and binary artifacts if you change the version numbers in the URLs here: https://typesense.org/downloads/

You'll also find Docker images for both architectures [here](https://hub.docker.com/r/typesense/typesense/tags). Note that for RC releases, you need to pull the specific CPU architecture you need by tag, unlike for GA releases where the CPU architecture is automatically determined by docker, just with the version tag. 

Native macOS binary build still involve a non-trivial amount of effort to automate, so we'll only be publishing these builds for GA releases for now. But you can now use the docker arm64 builds on M1/M2.

**Comment by sashahilton00** [comment]
Ah perfect, I missed the `-arm64` suffix when updating. Is there any reason for the architectural suffix rather than just publishing multi arch tags to docker?

**Comment by jasonbosco** [comment]
The ARM and AMD builds run independently on different machines and I assumed that I'd have to coordinate with the build completion events somehow to then push a multi-arch docker manifest. But I just learnt that I can actually run the docker manifest commands on each architecture box independently and amend it as each arch build completes. 

Just tested this on 0.25.0.rc61 which is now a multi-architecture docker build with the tag `typesense/typesense:0.25.0.rc61`. I'll publish multi-arch manifests for rc59 and future builds going forward. 

Thank you for the nudge to look into this!

**Comment by sashahilton00** [comment]
No problem, thanks for sorting it.
