### ISSUE TITLE
Explicitly specifiing subfields in nested arrays prohibits insertion

### ISSUE THREAD

**Issue by muneebshahid** [typesense/typesense#1042]
## Description

Unable to insert data when subfields for a nested array are explicitly specified in the schema. 

## Steps to reproduce

Create an index with the following schema.

```
{
    "name": "test",
    "enable_nested_fields": True,
    "fields": [
        {"name": "customer", "type": "object[]"},
        {"name": "customer.id", "type": "string"},
    ],
}
```

Attempt to create a doc with the following schema

`{"customer": [{"id": "a388d620"}]}`

## Expected Behavior

The document is inserted in the typesense.

## Actual Behavior

An error is raised 

```
RequestMalformed: [Errno 400] Field `customer.id` must be a string.
```

The schema works if either `customer` type is changed to `object` or `{"name": "customer.id", "type": "string"}` is removed. 

## Metadata

**Typesense Version**: Typesense v0.24.1

**OS**:

**Comment by jasonbosco** [comment]
Since `customer` is an _array_ of objects, you want to set `customer.id` to `string[]`:

```json
{"name": "customer.id", "type": "string[]"},
```

On a side note, if you also add `customer` to the schema, the schema definition for that will take precedence since it is much broader and so all objects inside that array will be indexed. If you want to only index `customer.id` from each object, you can remove `customer` from the schema and just keep `customer.id` defined as a `string[]`.

**Comment by muneebshahid** [comment]
@jasonbosco Thank you so much. It worked like a charm. And thank you for the hint too. I wasn't aware about this either. I'll close the issue.
