### ISSUE TITLE
Possible to clear the server side cache?

### ISSUE THREAD

**Issue by zeluspudding** [typesense/typesense#1060]
Couple of questions that aren't super clear from the docs:
 - Is there a way to clear the cache on scoped API keys? I have a few use cases where the cache basically never needs to be cleared except after certain events.
 - In Typesense cloud, do requests served by cache contribute to the monthly bill? If so, is that just charged at the same rate of ordinary search data egress?

**Comment by zeluspudding** [comment]
Closing as I just realized the answer - I realize now that caching doesn't work globally across a cluster but instead only within client search sessions.

**Comment by jasonbosco** [comment]
@zeluspudding There's client-side caching in the JS library and you can also enable [server-side caching](https://typesense.org/docs/0.24.1/api/search.html#caching-parameters) in Typesense. 

> Is there a way to clear the cache on scoped API keys? 

Scoped API keys are never cached, since they are generated cryptographically in the SDK library you're using and are not stored in Typesense. 

> In Typesense cloud, do requests served by cache contribute to the monthly bill? If so, is that just charged at the same rate of ordinary search data egress?

Server-side cached requests still contribute to bandwidth usage and are charged. Where server-side caching helps is to conserve CPU capacity, so you can support more concurrency.
