### ISSUE TITLE
Handling realtime data with sorting

### ISSUE THREAD

**Issue by jd-0001** [typesense/typesense#107]
## Description

I am building site which lists item with sorting and searching. The issue I am facing is when new item is added to the database(also at the same time to typeSense). This creates pagination issue like below:
https://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/

Also, our items have upvote and price filters, how can we handle the above case for that also?
How to tackle this kind of scenario. I tried this on my own but I am unable to do it alone. So, advice will be really helpful.

**NOTE: I update typeSense document at the same time my database get an update.**

## Steps to reproduce

None

## Expected Behavior

None

## Actual Behavior

Currently, If I use pagination I am facing the issue similar to the above blog post link.

## Metadata

**Typsense Version**: v0.11.2(maybe)

**OS**: Linux Mint 19

**Comment by kishorenc** [comment]
Hi @jd-0001 -- the best way to tackle this is to add a timestamp field, say `index_time` to the indexed search record which indicates when the record was added. Once https://zapier.com/zappy have that, whenever you query be sure to include a index_time < now filter and preserve the now for future queries unless a lot of time elapses.

**Comment by jd-0001** [comment]
Hello, @kishorenc Thanks for the reply. I got your solution and it will work for sure. But, is there anything which internally handled by typeSense? Currently, I have used id < current_id(latest id at the time of making a request) logic. However, I have another related issue.

I also have likes & pricing of items that changes(upvotes constantly get changed). So, when a user likes the item it gets updated in typeSense server. I also have sort by likes. In this case, because item likes get updated in typeSense we encounter wrong pagination data like some items are appearing again on the next page(when likes increases). Another case is if someone removes like then that item also doesn't appear in the list.

Can we have any other internal way we can handle it because using timestamp is not enough in the above case?

We also have sort by price [ASC & DESC] but the price is not updated at the same frequency of upvote, so it is fine at some point.

Awaiting your response.

~ Regards

**Comment by kishorenc** [comment]
That's why I suggested using an index timestamp -- when you use `id`, it will remain the same during updates, but an `updated_at` timestamp field will be updated **anytime** you make an update to a document. 

In summary, add a `updated_at` int64 field to your schema. Now, whenever you update the document (for likes or prices), just update this field as well with current timestamp. Finally, when query, filter for `updated_at: < NOW_TS`.

**Comment by kishorenc** [comment]
@jd-0001 Did that work? Okay to close this issue?

**Comment by jd-0001** [comment]
Hi @kishorenc Thanks for your solution. Actually, it won't work in our case where we short by likes(upvotes) and likes gets updated constantly so updating the item's `updated_time` once the item is liked may miss the item while fetching for the next page.

I have another workaround but I don't know if it's efficient for TypeSense. Here it is:
I will create array of like ids(each like will have id) in each item. So, when the user first visits the TypeSense list I will set the current latest id somewhere and when the user scrolls down_(we use infinity scroll for pagination)_ then I will filter the collection by that array field.
```
# IDK how to filter arr as well
# Also how to sort by array fields length
?filter_by=item_upvtes[]<upvote_id&sort_by=item_upvotes[]count
``` 

So here are the main things I would like to ask on this approach:
1. Can we filter array
```
field_value = [1,4, 6,8,12,45,78,79,81]
# Filter above array filed value like `field_name[]<element_value`
```

2. Can we sort by length of an array(count of array element)
```
val1 = [1,2]      # Order 2
val2 = [4]         # Order 3
val3 = [5,6,3]  # Order 1
```

3. Is it good(memory, performance and etc) to store small integer value like ids in an array because that array may have 1k to 10k  values in it and also that array will get used to filter and sort?

Thanks for your quick responses.

~ Regards

**Comment by kishorenc** [comment]
Spent some time thinking through this.

> so updating the item's `updated_time` once the item is liked may miss the item while fetching for the next page.

The root of the problem seems to be in 2 conflicting goals:

a. Ensuring that the items are not duplicated during pagination
b. Surfacing up-to-date information in the search results

These two goals are inherently conflicting in nature. Depending on which is the lesser evil for a particular sorting order (e.g. sorting by date vs sorting by likes), you can choose one of the 2 following approaches:

To ensure that items are not duplicated, you can use the `max_hits` parameter (available in 0.12.0) and just fetch a larger number of hits in advance and do the pagination yourself. This way, you fetch a "frozen" set of results upfront but are just revealing it as and when user paginates or scrolls. As such, you are guaranteed that the results don't jump/duplicate. We will consider extending this to a server-side "snapshot" feature in future. 

If you are sorting items by date, then you can simply use the ID or `created_time` as a filter to ensure that the pagination does not result in duplicate items, but this will not show live results -- because showing live results WILL involve some duplication. 

As for the other questions you have asked:

1. yes you can filter on an array field by a given value
2. but you cannot sort results by the length of the array field
3. and I don't think this is a scalable approach

This problem is not unique to Typesense: any data store that stores changing data will face the same issue. And as far I can tell, the only way to approach this problem is either via a snapshotting (by using max_hits to prefetch results or if the database supported snapshot cursor) or by using a filter, as shown in the Sitepoint link you have shared.

**Comment by jd-0001** [comment]
Hi, @kishorenc Thanks for responding. We can close this.

**Comment by jd-0001** [comment]
Hi, @kishorenc I didn't want to bother you but if I filter the collection using below:
```
filter_by=modified_date:<1591119792257
```
modified_date is `int32`

TypeSense server stops saying below:
![Screenshot from 2020-06-02 23-40-02](https://user-images.githubusercontent.com/47495003/83554631-b9a48d80-a52a-11ea-9a75-26d7cbdf66d9.png)
![Screenshot from 2020-06-02 23-40-22](https://user-images.githubusercontent.com/47495003/83554638-bb6e5100-a52a-11ea-9f20-2fed0c38f64a.png)

Do you want to me to create another issue or this is fine?

Does int32 can fit timestamp??

Awaiting your response.

Stay Safe. Stay Home 🏠​
