### ISSUE TITLE
Build Failure on Mac 10.15

### ISSUE THREAD

**Issue by ankane** [typesense/typesense#119]
## Description

Hi, I'm hoping to add Typesense to Homebrew so Mac users can do `brew install typesense`. However, building from source is failing when building RocksDB.

## Steps to reproduce

Homebrew formula: https://github.com/ankane/homebrew-core/blob/master/Formula/typesense.rb

Commands:

```sh
mkdir build
cd build
cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/typesense/0.14.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
```

## Expected Behavior

Build succeeds

## Actual Behavior

When building RocksDB, it fails with:

```txt
  CC       util/crc32c.o
util/crc32c.cc:441:10: error: use of undeclared identifier 'crc32c_ppc'
  return crc32c_ppc(crc, (const unsigned char *)buf, size);
         ^
util/crc32c.cc:457:7: error: use of undeclared identifier 'arch_ppc_probe'
  if (arch_ppc_probe()) {
      ^
util/crc32c.cc:472:7: error: use of undeclared identifier 'arch_ppc_probe'
  if (arch_ppc_probe()) {
      ^
3 errors generated.
make: *** [util/crc32c.o] Error 1
CMake Error at cmake/RocksDB.cmake:39 (message):
  rocksdb-5.13.1 build failed!
Call Stack (most recent call first):
  CMakeLists.txt:52 (include)
```

Here are the full logs: https://github.com/ankane/homebrew-core/runs/840291068?check_suite_focus=true

(search for `==> cmake` for relevant logs)

fwiw, I'm seeing a different error with RocksDB outside of Homebrew (`./build.sh --package-binary`).

```sh
In file included from db/builder.cc:19:
./db/internal_stats.h:107:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_BYTES,
```

## Metadata

**Typesense Version**: 0.14.0

**OS**: Mac 10.15

**Comment by kishorenc** [comment]
The Mac static binary is already published for each release and is available here: https://typesense.org/downloads/

Can that be used for brew or is there a reason why you want to build from source? 

Over time, Typesense build has gotten a bit long and complex due to the number of dependencies. There are also various gotchas around static/dynamic linking library combinations. Although I primary develop on the Mac, I kinda gave up trying to make the Mac build easily reproducible. However, RocksDB should build cleanly since I remember rebuilding it a few months back. It could be an issue with the latest  Mac OS`10.15` as well.

**Comment by ankane** [comment]
Homebrew requires projects to be built from source, so can't use the binary for it unfortunately. If building from source on Mac is supported in the future, happy to revisit this.
