### ISSUE TITLE
Typesense doubles RAM consumption after restart

### ISSUE THREAD

**Issue by rluba** [typesense/typesense#121]
## Description

I’ve filled Typesense with a small example dataset (see #120). After creating the collection and adding 8830 documents, Typesense (0.14.0 in the official Docker image) required around 460MB of RAM:
<img width="546" alt="Before" src="https://user-images.githubusercontent.com/4600573/87144690-74514980-c2a8-11ea-82a7-bc2273e40e63.png">

After stopping and re-starting the container, Typesense required 878MB, **almost double the original amount**:
<img width="583" alt="After restart" src="https://user-images.githubusercontent.com/4600573/87144699-77e4d080-c2a8-11ea-8c35-abc43efb0115.png">

After deleting the entire collection (using `DELETE /collections/<name>`), RAM usage dropped only a bit – to 746MB.

Even after restarting Typesense again, it still required **714MB of RAM, even though there was no collection left**:
<img width="626" alt="After delete and restart" src="https://user-images.githubusercontent.com/4600573/87127483-46f7a200-c28e-11ea-8ab2-bf85dcd0d2ce.png">

## Steps to reproduce

1. Start Typesense docker container with the data directory on a volume:
    ```
    docker run --init --name typesense -p 8108:8108 -v $(pwd)/typesense-data:/data typesense/typesense:0.14.0 --data-dir /data --api-key=TEST
    ```
2. Create a new collection and import a large dataset 
3. Restart Typesense container -> RAM requirement doubles
4. Delete the collection -> RAM barely drops
5. Restart Typesense container -> RAM amount remains high

## Expected Behavior

* After step 3 RAM requirement should be the same as after step 2 (or lower).
* After step 4 or 5 RAM requirement should be back to the initial amount.

## Metadata

**Typsense Version**: 0.14.0 inside the official Docker image

**OS**: Ubuntu 20.04 LTS

**Comment by kishorenc** [comment]
@rluba We (and others) have certainly indexed datasets with N millions of records without issues previously. 

Can you please tell me:

1. What's the on-disk size of these documents?
2. How are you importing them -- by indexing individually or via the import end-point?
3. Can you share the schema being used? Feel free to use placeholder names for fields (if that matters).

**Comment by rluba** [comment]
1. 161MB for the whole typesense data dir.
2. They were imported via the `POST /collections/<id>/documents` endpoint.
3. Here’s the output of `GET /collections`:
```JSON
[{"created_at":1594369996,"default_sorting_field":"rank","fields":[{"facet":false,"name":"id","optional":false,"type":"string"},{"facet":false,"name":"path","optional":false,"type":"string"},{"facet":false,"name":"filename","optional":false,"type":"string"},{"facet":true,"name":"case_kind","optional":true,"type":"string"},{"facet":true,"name":"case_nr","optional":true,"type":"string"},{"facet":true,"name":"type","optional":false,"type":"string"},{"facet":false,"name":"content","optional":false,"type":"string[]"},{"facet":true,"name":"encrypted","optional":false,"type":"bool"},{"facet":true,"name":"embedded","optional":false,"type":"bool"},{"facet":false,"name":"rank","optional":false,"type":"int32"}],"name":"documents","num_documents":8830}]
```

But I don't understand how any of these things are related to the issue that restarting the Typesense container doubles the occupied RAM and that it’s not released when I delete the collection.

**Comment by kishorenc** [comment]
The tricky thing about measuring free memory is that `malloc()` will not return memory to the OS when items are deleted. Memory allocators can and do reuse memory when it's needed further from the same pool. For e.g. here's the same problem described in Redis documentation: https://redis.io/topics/memory-optimization#memory-allocation

Unless there is a regression, that could explain the haphazard memory usage. However, that does not explain the behaviour you are seeing completely so I am going to take a deeper look here to see what's happening.

**Comment by kishorenc** [comment]
@rluba Took a deeper look at the issues involved and I can confirm that the RSS memory size you are seeing is certainly not the true memory utilized by the process due to the way memory fragmentation and reuse works as I outlined in my previous comment. Typesense creates a lot of short lived and small heap allocations. This [answer](https://stackoverflow.com/questions/32343848/why-the-memory-not-freed-in-top-and-pmap/32344167#32344167) from Stackoverflow explains the behavior nicely.

The reason why you see a different value during a restart is because a different code path is taken for loading the on-disk documents into memory compared with index-time code path, so the data structures and hence the allocation pattern will differ. There is also an element of additional indirection involving Docker -- I'm not sure if there are additional gotchas with that.

The actual yardstick for memory consumption is 2-3x of on-disk data storage for typical indexing patterns. However, the memory growth **will not be linear** since most of the memory is used in indexing string tokens in an inverted index. After a certain threshold, as you add more documents, there will be very few new tokens added to this inverted index, so the memory growth will flatten out over time.

**Comment by rluba** [comment]
Thanks for looking into it. But that doesn’t explain why the memory consumption remains very high after deleting the whole colleciond and *and* restarting Typesense. (Step 5.)

**Comment by kishorenc** [comment]
1. The underlying allocator is not releasing the memory to the OS when a collection is deleted. I was able to reproduce the same issue on OS X with the Mac binary as well. However, the code is making all the necessary `delete` calls. 
2. When you restart Typesense, all the indexing happens once again from disk as we don't persist any on-memory data structures. So the same "allocation storm" happens again.

I'm sorry about how misleading all of this is. I'm looking into how we can expose a "true memory consumed" metric via the API to help assess things. Also working on reducing overall memory foot print further in the longer run.

**Comment by kishorenc** [comment]
> after deleting the whole colleciond and and restarting Typesense

Sorry I didn't fully grasp the implication of this line. Let me check this particular detail and get back to you.

**Comment by kishorenc** [comment]
@rluba Reason for memory allocation even after deletion of collection **and** after a restart:

1. All insert and delete operations on Typesense goes to a Raft log, which is primarily used for clustering. Even in single node mode, this log is useful for a replay in case the program crashes. This log is snapshotted every 10 minutes.
2. Let's say you:
    a. Index 100,000 documents onto Typesense
    b. Delete the corresponding collection immediately, and
    c. Restart Typesense
3. On restart, Typesense will start replaying the Raft log, which will first contain the 100K inserts. 
4. Next, it will find the "DELETE" log entry and will proceed to delete the collection and in-memory structures

This way, we will end up in the exact situation as before w.r.t. fragmentation and unreleased memory. 

**However**, since the log is snapshotted every 10 minutes, if you restart Typesense **10 minutes** after deletion of a collection, you will notice that the memory will be definitely free on restart since snapshotting of the log will ensure that the unwanted inserts before the deletion are purged.

What Typesense do to handle this gotcha: Typesense should probably trigger a snapshot of the Raft log every time the collection is deleted. This way, Typesense will not have to needlessly replay inserts preceding a delete on a restart.

Hope that clarifies things.

**Comment by rluba** [comment]
Thanks for investigating and explaining this. 👍

Just one final comment. You said:
> Typesense creates a lot of short lived and small heap allocations. 

That sounds like a serious anti-pattern to me – especially if you’re doing it with `malloc()` et al. Have you considered a bucket or pool allocator? (Slightly off-topic, I know.)

**Comment by kishorenc** [comment]
Typesense uses trie as the inverted index data structure so that we can support fuzzy search. Trie construction involves a lot of mutations as the trie grows in size (no way to know the exact way the trie will branch out so you cannot pre-allocate memory easily).

While Typesense does not use a custom allocator or an optimized memory allocator like jemalloc, the underlying default glibc memory allocator viz `malloc()` already pools the memory allocations for you. So `malloc()` [is not a direct system call](https://stackoverflow.com/a/6530429/131050). However, I think adopting a better allocator is a good idea. So there are essentially two problems that this issue has brought forth, namely:

1. Metrics that Typesense should expose indicating a) the true memory usage b) reserved but unused memory and c) memory fragmentation ratio (very similar to what Redis exposes). 
2. Use of a more efficient allocator like `jemalloc` that will improve performance, give us more knobs/levers and will also help in exposing the metrics.
3. In the longer term, identify places where we can avoid/reduce unwanted allocations

Adopting `jemalloc` for Typesense and exposing these metrics should be fairly -- I can get a build ready for you by the end of the week to try, if you are interested.

**Comment by kishorenc** [comment]
@rluba Typesense `v0.15.0` (just released) contains `jemalloc` integration and has much improved memory performance. The `/metrics.json` end-point also now exposes a number of memory metrics (e.g. `typesense_memory_active_bytes`) which hook into the allocator's stats so they give a more accurate picture of the actual memory usage. 

If you're still interested in giving Typesense another go, please let me know how I can help.
