### ISSUE TITLE
Benchmark embedding model

### ISSUE THREAD

**Issue by pakerekchdz** [typesense/typesense#1214]
Do you have a benchmark of embedding model auto - indexing time? I wonder how much CPU time it will take to index one million and ten million documents.

**Comment by jasonbosco** [comment]
Indexing time with auto-embeddings depends on the ML model and batch size. Here are some benchmarks I did on 10K dataset.

<img width="1023" alt="Screenshot 2023-09-09 at 10 30 31 AM" src="https://github.com/typesense/typesense/assets/458383/dcd68530-e12e-46a1-9fe5-82be9a2f9bbb">

The results should be extrapolateable to 1M records.

Adding a GPU (the rows with NVIDIA T4 above) for auto-embedding significantly improves auto-embedding performance for built-in models.

**Comment by schonert** [comment]
@jasonbosco thanks for sharing this! Will these embeddings be stored for next index or will typesense generate the embeddings again?

**Comment by jasonbosco** [comment]
The embeddings will be persisted to the index snapshot as soon as snapshotting runs (every hour by default), and after that if the Typesense process is restarted the embeddings won't be regenerated. But if the Typesense process is restarted before the hourly snapshot run, then the documents created/updated since the last hour will regenerate embeddings. 

If you don't restart the Typesense process, then this won't be an issue in normal course of operations. 

For regular updates, embeddings are regenerated only if the auto-embed field values are changed.
