### ISSUE TITLE
Feature request: Providing a custom URL for OpenAI auto embeddings

### ISSUE THREAD

**Issue by aborzanovic** [typesense/typesense#1260]
## Description

I was hoping to use the auto embedding feature, but the URL is hardcoded to OpenAI API and I'm using it on Azure.

**Comment by jasonbosco** [comment]
Unfortunately it looks like the API signatures are different in the Azure version of OpenAI. So we would have to add support for Azure OpenAI as a separate remote embedding service. 

Will leave this open as a feature request to track demand.

**Comment by nick16180** [comment]
Would it be possible to add support for a generic API that returns embeddings? I too would like to add Azure for OpenAI, but it would be nice if this was generic for any embedding API.

**Comment by jasonbosco** [comment]
We're tracking the generic API use-case in #1318 - but that would require Typesense to enforce an API contract that the external API needs to adhere to. 

For public embedding API providers, we would still have to add support on a case-by-case basis, since every provider has their own API signatures.

**Comment by kristiankielhofner** [comment]
Providing a custom URL would also allow for the use of other wire-compatible LLM implementations, providers, and serving frameworks. Best example probably being [vLLM](https://github.com/vllm-project/vllm/blob/main/examples/openai_chatcompletion_client.py).

**Comment by jasonbosco** [comment]
Released in v26

**Comment by nascosto** [comment]
Is there documentation on this? I'm not seeing it on the semantic search page.

**Comment by jasonbosco** [comment]
Looks like we missed documenting this. 

Just added it here: https://typesense.org/docs/26.0/api/vector-search.html#using-openai-compatible-apis

**Comment by nascosto** [comment]
Thanks!

**Comment by zehawki** [comment]
Actually this won't work for Azure OpenAI. The Azure API signature is:

`POST https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/embeddings?api-version={api-version}` via https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings

But TS will insert a `/v1/embeddings` at the end

Also, API key is needed as `api-key: YOUR_API_KEY` rather than openAI `Authorization: Bearer $OPENAI_API_KEY`.

It would be great if Azure could be supported. After OpenAI themselves, MS has the largest OpenAI infra.

**Comment by jasonbosco** [comment]
@zehawki I'm surprised to hear that Azure uses a different API format, but could you open a new GitHub issue for Azure, so we can track it?

**Comment by zehawki** [comment]
@jasonbosco Done! #1828
