### ISSUE TITLE
Last fields in my query are sometimes completly ignored and are not being searched

### ISSUE THREAD

**Issue by BekaArabidze98** [typesense/typesense#1321]
Hello.
I have this case. I search for by 4 queries - `query_by=name,description,responses,request`
I know that if no query_by_weights are not provided then fields earlier in the query_by list will be considered to have greater weight. because of this sometimes the results that I have in my request field are completely ignored are search results are not returned at all.

when I move a request, for example, after the name then everything is great. but now my descriptions are not being searched. Is there a way to balance these behaviours? I also tried to use query_by_weights nothing really changed.

`query_by=name,description,responses,request&per_page=10&query_by_weights=1,1,1,1` - this is how I have right now.
I tried to add more weight to request and response, but then again, my name and description query results were lost.

Thanks for the help :)

**Comment by jasonbosco** [comment]
The default behavior in Typesense is `text_match_type: max_score` which means that the field that matches first in the list of `query_by` is used as the representative score to rank results. 

You might want to try setting `text_match_type: max_weight` to see if that helps with your use-case.

**Comment by BekaArabidze98** [comment]
thanks a lot. I will try that

**Comment by Muffinman** [comment]
I'm actually having a very similar issue in my use case. Changing `text_match_type` does not seem to have any positive effect.

Unfortunately it's not straightforward to compile into a set of reproducible CURL commands because it's a fairly large dataset (120k items). While I try to compile a proper example here's some screenshots an example query strings.


![Screenshot 2023-11-02 at 14 42 40](https://github.com/typesense/typesense/assets/1319568/49057e29-8575-4236-b003-6ee6f6259e5e)

![Screenshot 2023-11-02 at 14 42 56](https://github.com/typesense/typesense/assets/1319568/c73439be-62d3-414b-b224-4fc5ec6487c1)

`http://localhost:12345/collections/products/documents/search?query_by=title,parents,content&query_by_weights=5,3,1&filter_by=published:=true&page=1&per_page=6&text_match_type=max_weight&q=JCB+Air+Vent+round`

It almost looks like it totally ignores any tokens after the third in the query string. Is that possible?

**Comment by jasonbosco** [comment]
> It almost looks like it totally ignores any tokens after the third in the query string.

Not unless it's a bug... It would be great if you're able to share a minimal dataset + curl commands to replicate the issue you're seeing to debug this further.

**Comment by Muffinman** [comment]
I managed to create a gist here with a minimal set of products. This seems to exhibit the same behavior.

https://gist.github.com/Muffinman/24aa0884f72340aaf4c6ef982325dbe1

**Comment by BekaArabidze98** [comment]
For my use case, which I posted earlier, `text_match_type: max_weight` worked and I also have ` query_by_weights=1,1,1,1`
Thanks for the response.

@Muffinman I hope your problem will be resolved too.
Have a great day

**Comment by kishorenc** [comment]
@Muffinman 

Thanks for sharing that gist. I tried the queries on the dataset. There are no records that contain all the word in the query (jcb, air, vent, round). 

In such a scenario, Typesense proceeds to drop words in the query from right to left until results are found. 

1. When the query `JCB+Air+Vent+round` is made, the last word `round` is dropped and we are able to find records with the other words matching.
2. However, when the query `JCB+round+Air+Vent` is made, the last word `vent` is dropped and matching records with the other words in the query are found.

Since the words used for searching (after dropping of tokens) is different, the records fetched are also different.

**Comment by Muffinman** [comment]
That makes sense. Are there any params for specifying logic for dropping of tokens?

The docs are not totally clear on how the tokens are removed, they seem to suggest _BOTH_ that the tokens are dropped `left-to-right` / `right-to-left` and/or with `least results`? Removing the tokens with least individual results would certainly make sense, rather than choosing an arbitrary token.

> If drop_tokens_threshold is set to a number N and a search query contains multiple words (eg: wordA wordB), if at least N results with both wordA and wordB in the same document are not found, then Typesense will drop wordB and search for documents with just wordA. Typesense will keep dropping keywords like this left to right and/or right to left, until at least N documents are found. Words that have the least individual results are dropped first. Set drop_tokens_threshold to 0 to disable dropping of words (tokens).

It would be good if this could be clarified.

Thinking of a typical multi-word query, more-often the descriptive detail is added first and removing the end token would completely lose the context of the search.

`JCB round air vent` is a typical example where `vent` is really the key part of the search term and should not be removed.

Coming from the Elasticsearch world the complete removal of tokens at all is a little counter-intuitive, but I understand they are very different engines. I believe the default ES behaviour would be to individually query each token and sum the scores.

**Comment by kishorenc** [comment]
> Words that have the least individual results are dropped first. 

Sorry for the confusion about this: it was an earlier behavior. We now drop tokens strictly right to left first and if no results are still found, move to dropping left to right. 

In recent 0.25 RC builds, we have a way to control the direction. See here: 

https://github.com/typesense/typesense/issues/1162#issuecomment-1732979855

**Comment by Muffinman** [comment]
Thanks! I tried `drop_tokens_mode` = `left_to_right` and that has made a great difference for our use case.

I'm a sample size of 1 but I would say that `left_to_right` would make sense to be the default if your primary target is English speaking users.

**Comment by kishorenc** [comment]
Atleast for e-commerce, right to left makes sense because you usually have queries like "brand product_name version" where it's useful to return other versions when a specific version is not found...

But I agree that it's use case specific, which is why we've added a flag for this now!

**Comment by Muffinman** [comment]
I disagree because I think the less important adjectives will often come first.

`smart black trousers`
`white shirt`
`pleated skirt`

etc.

It would be interesting to look at some bulk stats for a large site and actually see how often the key term is first/last.
