### ISSUE TITLE
Highlight prefix matches instead of the full word

### ISSUE THREAD

**Issue by Grafikart** [typesense/typesense#136]
## Description

I noticed that highlight acts a bit strange when you search a world partially. The highlight seems to wrap the whold word instead of doing an exact match.

![highlight](https://user-images.githubusercontent.com/395137/96295875-a8967d80-0fee-11eb-9e43-1ce7d167d33f.png)

## Steps to reproduce

Nothing specific, here is my query

```php
$query = [
            'q' => $q,
            'page' => $page,
            'query_by' => 'title,category,content',
            'highlight_full_fields' => 'content,title',
            'per_page' => $limit,
            'num_typos' => 1,
        ]
```

## Expected Behavior

I would expect the highlight to be restricted to the searched term.

## Metadata

**Typesense Version**: Docker : typesense/typesense:0.15.0

**Comment by kishorenc** [comment]
👋 @Grafikart 

The highlighting marks the word that is matched to the search query token. This could be a prefix match or an exact match. In both cases, the whole word is highlighted in the result. Are you suggesting that the highlighting should cover only the prefix, so something like this?

```
<mark>symfo</mark>ny
```

**Comment by Grafikart** [comment]
Yeah this was my suggestion but the more I think about it the more I think it could be done manually (I dunno if this feature adds extra complexity in the code)

**Comment by ckeller03** [comment]
@kishorenc That's my expectation as well as a user of another similar system, I want only the matching letters highlighted. It's much more intuitive that way to see the results change/narrow as you highlight each letter in the results. 

Additionally, there's another subtlety to this issue that's a bit more egregious. If you type 2 letters and the typo tolerance kicks in on only those two letters but highlights the whole world, it looks totally wrong. For example, if you search for "gr", it might bring back words that start with "cr", but since it highlights the whole word, it looks like the system is bringing back things that make no sense. (cc @jasonbosco from what I demo'ed to you)

**Comment by jasonbosco** [comment]
We've addressed this in this RC (docker) build: `typesense/typesense:0.23.0.rc15`.

Would love to get your feedback @ckeller03!

**Comment by AlexHengWork** [comment]
Hello @jasonbosco , was wondering if we could have the non-container version or the binaries for this 
RC (docker) build: typesense/typesense:0.23.0.rc15?

Thanks plenty!

**Comment by jasonbosco** [comment]
@AlexHengWork Here's a DEB version: https://dl.typesense.org/releases/0.23.0.rc28/typesense-server-0.23.0.rc28-amd64.deb. You should be able to extract the binary from the DEB file as well.

**Comment by lmucha-star** [comment]
Hello, sorry to bother, but I noticed some inconsistent behavior related to this issue. Now, this searched term is being highlighted, but only when the word starts with it. If you specify term `ymfo` from original report, then you'll still get whole word highlighted.
