### ISSUE TITLE
Optimize Search Analytics by Excluding Type-Ahead Queries Until Final Submission

### ISSUE THREAD

**Issue by Clasyc** [typesense/typesense#1551]
Is it possible to avoid collecting type-ahead searches altogether and only collect the query if the user clicks "enter" to view the full search results page? I imagine front-end could send an additional `query` parameter or `header` that indicates -> hey, I want this search to be included in the search analytics. 

Because even with [different delays](https://typesense.org/docs/0.25.2/api/analytics-query-suggestions.html#aggregation-key) configuration we still experiencing partial words and unfinished queries to be included. If we discard suggestion type-ahead searches and include only "final" user queries that would make situation much more easy to handle for us.

Maybe this would resolve if I simply set unreasonably long pause for `analytics-flush-interval`?

**Comment by kishorenc** [comment]
Currently, we treat a query as "final" if there is atleast a 4 second pause between a search query and the next. We could see if we can make this interval configurable but I think that's not the problem here. In type ahead use cases, sometimes, the user will simply not press an enter key at all because they will likely find what they are looking for before they finish typing their query fully. 

In 0.26 builds, we do have an option for Typesense to save the expanded form of the query. This can be enabled by setting the `expand_query: true` parameter when creating the analytics rule. This way, prefix queries are expanded to the full form of the first document that was returned.
