### ISSUE TITLE
Typesense increase num_documents after restart

### ISSUE THREAD

**Issue by djklim87** [typesense/typesense#1769]
## Description

I already have a collection with some amount documents (1165440). After restarting when I call API I see an increasing `num_documents` count. It's looking very weird. It means if I perform some requests right after the engine becomes available, it will look only at the already loaded dataset (say 1000 rows). I also don't see any records in the log that the preread ended successfully, which can help me catch when DB became available. 

## Steps to reproduce

1. Create some dataset
2. Restart engine 
```
# docker stop typesense_engine && docker start typesense_engine
typesense_engine
typesense_engine
```
3. Wait some time until engine becomes available
```
# curl -s -H "X-TYPESENSE-API-KEY: abcdef"  "http://localhost:8108/collections/hn_small/"
{ "message": "Not Ready or Lagging"}
.....
# curl -s -H "X-TYPESENSE-API-KEY: abcdef"  "http://localhost:8108/collections/hn_small/"
{ "message": "Not Ready or Lagging"}
```
4. When it is available start just calling collection:
```
# curl -s -H "X-TYPESENSE-API-KEY: abcdef"  "http://localhost:8108/collections/hn_small/" | jq .num_documents
191865
# curl -s -H "X-TYPESENSE-API-KEY: abcdef"  "http://localhost:8108/collections/hn_small/" | jq .num_documents
213868
```
And after some time it reached 1165440 count

## Expected Behavior

Maybe some startup flags or at least sone record in log, that shows that pre-read completed

## Metadata

**Typesense Version**:
```
% curl -s -H "X-TYPESENSE-API-KEY: abcdef"  "http://localhost:8108/debug/"  
{"state":1,"version":"26.0"}
```
**OS**:
Docker image: `typesense/typesense:26.0`

**Comment by jasonbosco** [comment]
On each restart, Typesense will first load the most recent snapshot (which happens every 1hr by default) and then replay the writes since that snapshot on to pop that to build the in-memory index. 

So if you do a lot of writes and restart Typesnese immediately, then you there's no snapshot and essentially all writes are replayed. You can control the threshold at which the node will be considered healthy after processing these replayed writes using the `healthy-read-lag` and `healthy-write-lag` parameters documented [here](https://typesense.org/docs/26.0/api/server-configuration.html#resource-usage).

Alternatively, if you take a [manual snapshot](https://typesense.org/docs/26.0/api/cluster-operations.html#create-snapshot-for-backups) just before restarting, then this issue shouldn't exist.
