### ISSUE TITLE
evaluating and comparing Typesense with alternatives 

### ISSUE THREAD

**Issue by srconklin** [typesense/typesense#178]
This project looks very promising. I am in the middle of evaluating it along with some of its alternatives.
I was browsing on the meiliSearch resources  at
[https://docs.meilisearch.com/resources/comparison_to_alternatives.html#about-meilisearch](url) 
and came across a few comments referencing Typesense that I hope you can comment on:

> Typesense uses a default_sorting_field (opens new window)on each document, it means that before indexing your documents you need to compute a relevancy score for Typesense to be able to sort them based on your needs.
> On the other hand, MeiliSearch uses a bucket sort, which means that there is a default relevancy algorithm based on the proximity of words in the documents, the fields in which the words are found and the number of typos. And you can still add your own custom rules if you want to alter the default search behavior.

is this true? 

> ... the most similar solutions to MeiliSearch are Algolia and Typesense. The three of them are search-as-you-type relevant search engines.
> Typesense is a great tool but is not recommended for achieving a lot of operations with minimal configuration.

Is this true? 

> Typesense aims to be simple to set-up and focus on developer productivity and experience by providing a clean API. It is best suited for light projects.

What is meant by a light project?

**Comment by jasonbosco** [comment]
Hi @srconklin, thank you for bringing this up. I had only seen the blurb about `default_sorting_field` previously in Meilisearch's docs. The other two blurbs are puzzling to me and I'm glad you pointed them out, so I can address all of them.

re: `default_sorting_field`: 

> it means that before indexing your documents you need to compute a relevancy score for Typesense to be able to sort them based on your needs

This is a common misconception and is not true. You could set `default_sorting_field` to a constant integer value for all records and Typesense will still pull up results based on just the keyword relevancy score it computes automatically by default, just like Algolia and Meilisearch. 

However in our experience working with search engines (not just Typesense) and large datasets, keyword-based relevancy scoring only gets you so far, especially in large enough datasets where many records might have similar/overlapping keywords and so end up having the same computed keyword-relevancy score. So you eventually end up having to set up custom ranking rules to tie-break records having the same keyword-relevancy score. 

This is where the `default_sorting_field` comes into play - _for tie-breaking_, when the keyword-relevancy score is identical for similar looking records. In Algolia and Meilisearch, you'd need to keep an eye out for when this happens as you index records over time and then define custom ranking rules separately to break ties. 

In Typesense, `default_sorting_field` is just a "custom ranking rule". We wanted to elevate the importance of defining a tie-breaking field upfront, especially if you have a good data point already (like say number of page views in the case of indexing web pages, or number of purchases in the case of indexing products, etc). We did this because most search applications eventually end up needing this tie-breaking mechanism and so we took the approach of having users think about it upfront, so search relevancy continues to stay good as you index more and more records. 

Now, if your dataset doesn't have a field that could be used for tie-breaking, that's totally fine as well - like I mentioned above, you can just set `default_sorting_field` to say `10` or any constant integer for all records and effectively turn off this feature. Typesense will then just go off of keyword-relevancy score, just like Algolia and Meilisearch.

> ... the most similar solutions to MeiliSearch are Algolia and Typesense. The three of them are search-as-you-type relevant search engines.

The three of them are indeed optimized for powering search-as-you-type experiences. However, MeiliSearch seems to take the approach of replicating Algolia's feature _implementations_ verbatim to a fault and so have unfortunately inherited some of Algolia's quirks in the process. With Typesense, we've architected each feature from the ground-up and in the process have solved important limitations in Algolia (and Meilisearch). 

A good example of this is the sorting feature. In both Algolia and Meilisearch, if you need to allow your end users to sort by a certain field (for eg: sort by price, sort by reviews, etc) you'd need to define these upfront at indexing time and internally they create replica indices which duplicate your *entire dataset*, one for each sort order (sort asc by price, sort desc by price each require separate indices). In Algolia's case these duplicate records count towards your usage which balloons cost and in Meilisearch's case, it ends up increasing your RAM requirements by multiples of each sort order you need for each field, which also increases your infra costs. 

In Typesense, you can instead define field-based sorts dynamically at query time using the `sort_by` parameter of the search endpoint. There are no duplicate indices created and so you save on memory requirements and infra costs. 

This is just one of several examples. 

> Typesense is a great tool but is not recommended for achieving a lot of operations with minimal configuration.

I'm puzzled and frankly a little disappointed that the Meilisearch team would make this claim. Typesense's explicit stated goal is to make high-performance out-of-the-box search accessible to all developers with minimal configuration and minimal operational overhead. We've been chipping away at this goal for just over 5 years now, we've heard about teams switching from Algolia to Typesense in production, we try to be on top of any issues and questions, and so I'd like to think that we got something right! 

It's hard to address a broad unsupported statement like that, but if you notice any thing missing or confusing with Typesense, please free to open an issue and we're happy to get to the bottom of it!

> It is best suited for light projects.

This is another head-scratcher of a statement! Not sure, what they mean by "light projects". 

In terms of dataset size, here's a showcase showing Typesense in action on a **32 Million songs** dataset: https://songs-search.typesense.org/. Most results should be returned in 50-60ms. 

Here's another showcase showing Typesense in action on a **28 Million books** dataset: https://books-search.typesense.org/

And another showcase with **2 Million recipes**: https://recipe-search.typesense.org/

In terms of concurrency, I've tested a dataset with ~3 million records (Amazon product data) that was ~13GB on disk and I was able to achieve a throughput of **250 concurrent search queries per second** on a 16GB RAM, 8-vCPU 3-node Typesense cluster.

So I'd have to strongly disagree with Meilisearch's yet another unsupported and broad claim. 

Finally, one thing that makes Typesense closer to Algolia than Meilisearch is that in addition to being able to self-host Typesense on your own infra, we also launched a hosted SaaS version of Typesense called Typesense Cloud earlier this year: https://cloud.typesense.org/, complete with a CDN-like infrastructure that can serve search queries from nodes closest to where your users are (we call it Search Delivery Network). 

Also, unlike Algolia which restricts index sizes to a maximum of 128GB even on their highest enterprise tier, we support index sizes of up to 768GB in Typesense Cloud, with no limits on the number of indices / collections you can create.

Typesense Cloud still runs the same open source version of Typesense, so this helps us dog-food our own product and also keeps us honest about making sure Typesense is super easy to deploy and operate, if only just to keep our own overhead low when operating Typesense Cloud! This helps improve the product for teams that choose to self-host Typesense as well.

Hope that helps, please let me know if I can clarify anything above. 

And thank you once again for bringing this to my attention!

**Comment by jasonbosco** [comment]
CC: @JimTeva Please see above ^. CCing you, since you had thumbs-up-ed this question.

**Comment by srconklin** [comment]
@jasonbosco NO problem...and thanks for the detailed response. I have been researching your product for the better part of the day, trying the demos you list and am beginning to come to the same conclusion about robustness and performance. 
I am in fact, going to set up the server using the Docker option on my local machine (Windows user) and test swapping out the Algolia Search with the TypeSense for the Instantsearch.js app that I am now testing in a few hours.

Admittedly, I was a bit taken back by one of the sites in the showacase.MD where the performance was less than optimal,  
[https://furn.nl/banken](url), but then I saw the song and book demos and was pleasantly surprised by the the zippy, performance. 

Do you think this is because the Dutch website is self-hosting their server? ...OR is the song demo site fast because it is running as a 3 region cluster in the cloud? 

After testing it all out on my local machine, my next task to evaluate if I can self host (in a docker container in production?)  or  
go for the SaaS cloud solution where I *think* the $15/month configuration would be enough?  
I am not sure how to estimate my needs.  I can say that I don't have that much data at all.  2,600 product listings in total.
The JSON file that represents the entire dataset that I currently am importing into Algolia is only 1,626 KB.

Would this give you a sense to put into perspective of what I can safely configure? 
Do you think self-hosting would good enough?

**Comment by jasonbosco** [comment]
> I am in fact, going to set up the server using the Docker option on my local machine (Windows user) and test swapping out the Algolia Search with the TypeSense for the Instantsearch.js app

Awesome! Let me know if you run into any issues. If you're using Vue / Laravel by any chance, this account from a user who switched from Algolia to Typsense might be helpful: https://laracasts.com/discuss/channels/guides/replacing-algolia-with-typesense-for-fuzzy-searching

> Admittedly, I was a bit taken back by one of the sites in the showacase.MD where the performance was less than optimal,
https://furn.nl/banken, but then I saw the song and book demos and was pleasantly surprised by the the zippy, performance.
> Do you think this is because the Dutch website is self-hosting their server? ...OR is the song demo site fast because it is running as a 3 region cluster in the cloud?

furn.nl uses Typesense Cloud, but in a single (geo) region configuration, running out of Europe. They have not enabled the Search Delivery Network feature for their cluster. (This information can be gleaned by looking at the network requests that are made by the site, so I didn't divulge any private customer information :) ).

So if you're accessing their site from the US, the latency you're seeing is network latency between Europe and the US. You can confirm this by looking at the `search_time_ms` field in the responses for any requests to the `typesense.net` domain on their site. This field gives you the true time required for Typesense to search through the dataset, minus network latency.

The songs demo is running on a 3-region cluster (with the Search Delivery Network feature enabled) in Oregon, Frankfurt and Mumbai. This helps cut down on network latency significantly for users around the world, which is what you observed. 

> After testing it all out on my local machine, my next task to evaluate if I can self host (in a docker container in production?) 
> or
> go for the SaaS cloud solution where I think the $15/month configuration would be enough?
> I am not sure how to estimate my needs. I can say that I don't have that much data at all. 2,600 product listings in total. The JSON file that represents the entire dataset that I currently am importing into Algolia is only 1,626 KB.

That dataset can definitely fit in 512MB RAM, which is the smallest configuration available in Typesense Cloud. If you choose to self-host, you should be able to get away with even a 128MB RAM machine for your dataset. 

For reference, I've managed to index 120K Amazon product names, categories, prices, brand names and ratings in a 512MB cluster in the past.

In general the RAM consumed by your dataset when indexed in Typesense, is roughly 2-3x the size it takes up as a JSON file on disk. The key factor that influences memory consumed is the number & type of fields you choose to index from your documents. Only indexed / searchable fields are stored in memory and the other fields are only stored on disk.

re: deciding between self hosting vs Typesense Cloud, I'd recommend thinking about it based on how much infrastructure you already run yourself. For eg: since you mentioned Docker, if you already have a mechanism to orchestrate Docker containers with persisted data volumes in production, then adding the Typesense docker container into the mix should be effortless and so self hosting will not be too much additional effort for you. Even without docker, you can also run Typesense natively on Linux servers with a single install command. You'd of course have to configure your server for the usual stuff you'd do on any server like setup firewall rules, monitoring, ssh keys, terraform / ansible configs (or not!), etc. If you already have to do this for other services in your app, then adding Typesense into the mix is very little additional effort. 

Now, if you don't already manage VMs or servers for your app (for eg: may be you're using serverless, or firebase, or Vercel, or similar products), and you don't want to worry about self-hosting a service, then Typesense Cloud would be a good fit, since it's point and click to provision new clusters. 

Finally, if you have users around the country / world and consistent network performance is critical, setting up a multi-region infrastructure across data centers can be quite involved when you're self hosting (based on our experience building Typesense Cloud!). With Typesense Cloud it's a flip of the switch to take advantage of the CDN-like infra we built. So that's another thing to consider. 

So I don't want to recommend one option over the other to you. The best option, as usual, is "it depends" on your context.

**Comment by JimTeva** [comment]
@jasonbosco Thank you very much for the detailed response, it helps a lot!

**Comment by jasonbosco** [comment]
@srconklin Thank you for pointing this out once again, I've opened an issue with Meilisearch mentioning these points and requesting that they update their docs appropriately: https://github.com/meilisearch/MeiliSearch/issues/1148

**Comment by jasonbosco** [comment]
Meilisearch has now updated their docs removing these statements.

**Comment by septatrix** [comment]
They have recently published a more exhaustive blog post comparing the two solutions: https://blog.meilisearch.com/meilisearch-vs-typesense/

I am not experienced in the matter or if they ran it by any of the typesense maintainers but it might be a good idea to check that they did not miss anything.

**Comment by JimTeva** [comment]
Not sure about this part: "Both products offer semantic search capabilities. However, Meilisearch can handle the generation of vector embeddings for you, freeing you from setting up additional infrastructure to benefit from AI. These are powered by AI and large language learning models via third-party tools, including OpenAI." because Typesense does "Vector & Semantic Search
Automatically generate embeddings using built-in ML models or OpenAI / PaLM API and do semantic search or nearest-neighbor search."
