### ISSUE TITLE
field parameter 'store' behaviour?

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#1797]
## Description

Could you please clarify the expected behaviour of the schema field 'store' parameter. What happens if using `'index': false, 'store': false`. Also what happens if using `'index': true, 'store': false` and then restarting typesense or rebooting the server. With the indexed fields gone, and no way to retrieve them from disk.

Also please check out following behaviour:

Create a collection with a schemafield that has `'index': false, 'store': false`. No error, not even when making it non-optional (the latter does error at indexing time when not supplying a value for that field).

The created schema returned (or retrieving the collection) does not show the 'store' parameter in the field, so there's no way of telling eg. if the parameter was overridden.

Create a collection with a field that has `'index': true, 'store': false` Index a document including a value for that field, and then get the document. The field/value isn't there, while it should be retrievable from the index.

## Metadata

**Typesense Version**:
26.0

**OS**:
windows 10, wsl  (Ubuntu 22.04.3 LTS)

**Comment by kishorenc** [comment]
With `store: false` we remove the field present in the doc before persisting it on disk. This is primarily for things like image embedding, where you have to send the image data but don't really want to store it because you only send it so that the model can embed the data.

With `index: false` you are telling Typesense not to do any in-memory indexing of that field. This is the same as not having the field in the schema at all. The reason we support this is because for some nested fields you might want a parent configuration with `index: true` but want to exclude specific child fields with `index: false`. 

> The created schema returned (or retrieving the collection) does not show the 'store' parameter in the field, so there's no way of telling eg. if the parameter was overridden.

This is mostly an oversight, will fix. 

With the above clarifications, can you please tell me if you find any other odd behavior with these flags?

**Comment by unclescooby** [comment]
Thanks for clearing that up. I suggest adding info re `store: false` usage for embedding to the collections fields parameters doc.

> With the above clarifications, can you please tell me if you find any other odd behavior with these flags?

Yes, as stated my last paragraph a value sent to a field with `'index': true, 'store': false` should be returned with the doc, as it's indexing in memory. Or if that combination is problematic with persistance (ie after reboot/crash) maybe it should not be possible.

**Comment by kishorenc** [comment]
> Yes, as stated my last paragraph a value sent to a field with 'index': true, 'store': false should be returned with the doc, as it's indexed in memory. 

This is not possible because the index is an inverted index of tokens => document IDs that contains those tokens. We cannot reconstruct the raw data from that index. The `store: false, index: true` combination only makes sense for "derived fields" where we want to populate a new field during indexing but throw away and not store the source of that field's data. This is often the case with embeddings of images or large documents because those large entities will anyway be present in an external data store that will populate the UI so they are needed to be kept in Typesense. In other cases, it does not currently make sense.

**Comment by unclescooby** [comment]
In that case the combination `store: false, index: true` doesn't make sense to me at all, and shouldn't be allowed. Obviously TS would still be able to ingest the value sent for use in derived fields. How TS handles that is not a user concern imho.

**Comment by kishorenc** [comment]
There is a real use case for `store: false, index: true` in the case of image embedding that I described above.

**Comment by unclescooby** [comment]
Could you give me an example schema please? Or is there one in the docs?

**Comment by kishorenc** [comment]
In the following example, image will be sent in base64 encoded form but we won't actually store it. We will only use it for generating the embedding for the image.

```
{
  "name": "Images",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "image",
      "type": "image",
      "store": false
    },
    {
      "name": "embedding",
      "type": "float[]",
      "embed": {
        "from": [
          "image"
        ],
        "model_config": {
          "model_name": "ts/clip-vit-b-p32"
        }
      }
    }
  ]
}
```

**Comment by kishorenc** [comment]
> But I mean an example with nested fields as you described above, and with a store: false, index: true somewhere in it.

AFAIK there are no other cases for this parameter. Still given that atleast one use case exist, we can't treat it as an invalid combination.

**Comment by unclescooby** [comment]
I see the store parameter has been added to the collection schema response. but It seems to get added always. What I wanted is to see it returned when explicitly defined in the schema. It should probably also be returned when the embed parameter is defined.

**Comment by kishorenc** [comment]
We won't differentiate between default and user-defined parameters. At best, we can return it only if it's set to `false` which will be a non-default value.

**Comment by unclescooby** [comment]
Ok, so I guess you have a set of default params for a field and then merge user-defined params.

Returning `store` only when it's set to `false` may be a good idea... if nobody has any objections to it. Thanks!

**Comment by unclescooby** [comment]
In retrospect, I can deal with the store parameter in my application.

Also, with the above example, I can set index: false and typesense will set it to true, ie without throwing an error, so I 'm ok with that for now.
