### ISSUE TITLE
Conditional sort with one parameter or another

### ISSUE THREAD

**Issue by andjela-aetherius** [typesense/typesense#1848]
Hi, I have a following use case and I would love your help with it (if it can even be achieved :))
I have a collection of Services. Service has _createdAt_ property (int32). Users can pay to refresh their service, in which case property _refreshedAt_ (int32) is set. _createdAt_ property is mandatory,  whereas _refreshedAt_ is optional. These properties are basic timestamps of when the service is created or refreshed.
I need to sort my services in descending order, either by createdAt, or by refreshedAt.

If service has _refreshedAt_ property (user paid to push their service on top), it should be sorted by _refreshedAt_, and _createdAt_ should be ignored. If not, _createdAt_ should be used for sorting. That means that some services should be sorted by refreshedAt, and others by createdAt, in the same query. 

Can this be done with typesense? 
I tried the following:
           "sortBy" : "refreshedAt: desc, createdAt: desc", but as expected, it sorts all services with refreshedAt first, and then all services with createdAt. 
           
Thanks in advance!

**Comment by kishorenc** [comment]
@andjela-aetherius 

It's not possible to do conditional sorting that way, but one way to solve this is by adding a new field called `refreshedOrCreatedAt` which is populated based on the same logic. If `refreshedAt` is present, it will use that value, otherwise it will be set to `createdAt`.

Then you can do the sorting in Typesense with this computed field.

**Comment by andjela-aetherius** [comment]
I assumed that's the case, so in the end we went with the solution similar to what you described. Thank you for your reply!
