### ISSUE TITLE
Dublicate with pagination

### ISSUE THREAD

**Issue by jc-skurman** [typesense/typesense#2055]
## Description

Send request for embedding filed with pagination
## Steps to reproduce

![image](https://github.com/user-attachments/assets/06fc1d7c-af66-4533-9bce-486d701ea129)
![image](https://github.com/user-attachments/assets/ea99a0ea-c49d-4a94-aeb2-cf76901ae73f)

## Expected Behavior

Response without duplicate
## Actual Behavior

Has duplicate
## Metadata

**Typesense Version**:
Latest
**OS**:
Ubuntu 24

**Comment by kishorenc** [comment]
Set an explicit `k` value for vector query. Otherwise the `k` value varies based on pagination. This can throw up duplicates.

Deep pagination does not work well with vector search without an upfront `k` value that pre-fetches the result. This is because due to the approximate nature of search, as the search radius (k) expands, more relevant documents could be found which affects overall ranking, which leads to a duplication effect.

This is unlike keyword search where we already have documents that match keywords in an inverted index which we are able to paginate in a deterministic manner.
