### ISSUE TITLE
Facet counts do not match results

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#222]
## Description

Facet counts are lower than expected - or filtered search results are higher than expected ;)

## Steps to reproduce

On https://songs-search.typesense.org/
* on the input type "e"
* Release_date: select "1950s"
* Release_type: select "Single"

## Expected Behavior

With the current data I'm seeing 65 results.
Sum of artists facet counts:  52   (5+5+4+4+4+3+(13*2)+1)
Sum of genres count: 5

I'd expect sum of facets count (for each field) to be the same as results, except when documents have more than 1 value for a field, eg when a song is in more than 1 genre the sum of genre facet counts would have to be higher than # of search results.

EDIT: rephrasing a bit: it's possible that search results are higher than sum of all counts for a particular field: if there's documents that don't have a value for that field and no facet for that field is selected. As soon as a value is selected, filtering for that field would kick in.

So, after the steps to reproduce, then if I click on Artist Lester Flatt....(5), I expect to only see 5 filtered songs in the search results!

## Actual Behavior
1. If I click on Artist Lester Flatt....(5) I get 10 results where I was expecting 5. There's duplicate songs, but I don't think facets would only count unique songs (even if it would, there's still 6 unique songs if I counted right). This indicates the facet count is too low. It seems that your code for facet counting uses other criteria than the code for search results. Or maybe there was some encoding in the artiest field that the counting routines choked on???

2. After unchecking artist, if I click on genre Jazz(3) I get 9 results instead of expected 3. I'm also seeing other genre facets appear that weren't there previously,.. probably because typesense previously returned count=0 for those. Maybe those got reactivated because they were in an array together with "Jazz" ? If I then click on Vocal Jazz(1) that facet updates to Vocal Jazz(4)
 
That makes me wonder if there's an issue with counting values in arrays.

It could be that if a document has genre Jazz and Vocal Jazz, and I select genre Jazz that the search results also includes documents with genre Vocal Jazz, even when I didn't select that.

Or it could be that if no values are selected the facet count routine only counts 1 of the values in arrays (or does not count anything in arrays at all), but if I select a value it will also count values in arrays where selected value is present.

EDIT: oops... maybe this issue should have been posted in the typesense repository

**Comment by unclescooby** [comment]
One more thing FYI: when the demo was still doing multiple requests, I think the first response appeared to have proper counts. It was the subsequent requests/responses that were showing lower counts. Please check that out.

**Comment by kishorenc** [comment]
> If I click on Artist Lester Flatt....(5) I get 10 results where I was expecting 5. 

I will have to look into this in more detail (especially the facet counts), but I think atleast the above observation is because more tokens matching the query prefix are considered when a filter is also added (`artist` in this case). Imagine have 10 words that begin with the letter `e` (the `query`). When you make a query without an `artist` filter, only the first, say 3 words are needed before enough results are available for search termination. Due to performance reasons we cannot exhaustively go through every token matching a prefix like "e", but only top K tokens as determined by default sorting field values associated. Now, when the additional artist filter is added, a lot less documents could match the first 3 words, so perhaps a 4th word is considered, and that can pull up more results.

**Comment by unclescooby** [comment]
Are you saying that a search without a query - ie. faceting only - would likely show more accurate counts? Would results be more accurate with smaller collections? Is there any way to configure speed vs accuracy?

Hope you will check out the [counts in the first response](https://github.com/typesense/typesense-instantsearch-adapter/issues/10#issuecomment-720730138) of a non multi-search request. Thanks!

**Comment by kishorenc** [comment]
@unclescooby I went through this in more detail. The sum of the facet counts don't match number of results because only top 20 facet values are returned, and there are also many records without values for the faceted fields.

I will now explain why the counts are more when you drill down further.

Typesense's goal is to return the *top matching* results for the given given query + filters as per the sort_by criteria. For a single character prefix like `e` there are possibly thousands of words/tokens that begin with `e`. Each of these words will have many documents matching the given query + filter. But not all documents of every such token might be top matches (based on the sort criteria). Initially when you are not yet drilling into a specific filter, Typesense will stop when there are sufficient results since the goal is not to return ALL results but to surface the most relevant results. However, when you drill down further, more tokens are considered to return more results, in this case, everything. If you want searches to be more exhaustive, you can tweak the `typo_tokens_threshold` and `drop_tokens_threshold`.

**Comment by unclescooby** [comment]
Thank you for clearing that up!

**Comment by unclescooby** [comment]
Not sure where to put this, but refering to the "e" query parameter above. My use case is to immediately show search results and facets without the q parameter (or make it optional if possible), and none of the demos allow me to do that. Would it be possible to at least set up one of the demos without the q input? Or maybe the ecommerce demo that you're preparing will have it like that? I did see the furn.nl website mentioned somewhere and their facet counts match results count, so thats good!!!

**Comment by kishorenc** [comment]
Are you looking to query the dataset with just filters and facets without any keyword? You can use `q=*` for that.

**Comment by unclescooby** [comment]
Yes, I'm aware of that. Thanks!

I'm trying to say that it may be useful for people to see a variety of possibilities being demonstrated, and for myself I'm curious about the speed and consistency of results without the q parameter on a several million documents dataset, before setting up my own ;)
