### ISSUE TITLE
Diagnosing slow search responses

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense#224]
## Description

Right now, I'm trying to diagnose why some search responses are really slow in production (i.e., up to 8-10 seconds per search). This is in regards to latency, not to  `search_time_ms`. While I'm not 100% sure the increased latency is from the Typesense server, I've ruled out most network issues.

### Background

I'm using Typesense with high availability with 5 nodes. Three nodes are in the US, and two are in Europe. That's to decrease the latency. Each Node is a Digital Ocean droplet, with 1GB RAM, 25 GB SSD disk, and 1 vCPU.

The slow searches seem to only occur when searches are performed in quick succession.

The slow searches seem to not be a result of the database size, as in development, I've tested Typesense with a much larger dataset.

While I can't confirm this, the slow searches are likely not a result of indexing operations happening at the same time.

### Logs

All the logs look unremarkable. Just what you'd expect, like "peer refresh succeeded". There have occasionally been some restarts (i.e. `systemctl status typesense-server` will indicate that there was an automatic restart), but these do not seem to be correlated with the slow searches.

### Theories/questions

- Most likely this seems to occur because the droplets have 1 vCPU. Hence multiple searches slows it down (does the searches sequentially). However, the `search_time_ms` is always very fast, much faster than the rate of searches needed for the slowdown. Have you experienced this before?
- Does the raft consensus algorithm impact search times? If so, is there any way to limit the refresh interval?
- Does having the nodes spread out geographically impact search times?
- Anything else I can look at to help diagnose the issue?

## Metadata

**Typsense Version**: 0.19.0 (deb)

**OS**: Ubuntu 20.04 (LTS) x64

**Comment by jasonbosco** [comment]
> up to 8-10 seconds per search). This is in regards to latency, not to search_time_ms
>...
> 1GB RAM, 25 GB SSD disk, and 1 vCPU
> ...
> Most likely this seems to occur because the droplets have 1 vCPU

Yes, this usually happens when the CPU is saturated. Could you check CPU metrics in the DigitalOcean dashboard (I think they show this), to verify if this is the bottleneck? 

Even if the CPU is not fully saturated, Typesense is multi-threaded and so there might be some level of contention going on between threads that handle searches and threads that handle other operations. Could you try upgrading the nodes to 2vCPUs and then may be 4vCPU to see if that resolves the issue?

> Does the raft consensus algorithm impact search times? If so, is there any way to limit the refresh interval?

It runs on a separate thread, so it typically doesn't affect search times. But then if the CPU is saturated and/or if there's high contention between threads, then this could happen. There is no way to limit the refresh interval - in HA mode, we want to detect downtimes as soon as possible, which is why we don't allow this to be configurable. 

> Does having the nodes spread out geographically impact search times?

No, reads are served by the node that the query is sent to, and don't involve other nodes. So geo-distributed clusters don't affect search times negatively. In fact, they should help reduce search times by reducing network latency between your users and the node.

> Anything else I can look at to help diagnose the issue?

Might be useful to check if there is a pattern to the queries that are typically slow, or if it's a random set of queries, by turning on [slow request logs](https://typesense.org/docs/0.19.0/api/#config-slow-request-log).

All this said, my primary suspicion is the number of vCPUs.

**Comment by Nick-Mazuk** [comment]
Looks like I never responded to this: yep, increasing the number of vCPUs did help. Thanks, Jason!

**Comment by elhe26** [comment]
hey @Nick-Mazuk, are you using volumes on each droplet? I'm trying to wrap my head on how to access data using 2 droplets but DO says you can connect 1 volume for each droplet. The issue here is that if you use a load balancer and you upload new data, you'll have data inconsistencies between the droplets. How did you resolve this issue? Thanks.

**Comment by jasonbosco** [comment]
@elhe26 When you setup Typesense in [clustered mode](https://typesense.org/docs/guide/high-availability.html), Typesense will take care of replicating data between all the nodes in the cluster. So you do not need to share disks between multiple droplets / VMs. Each droplet / VM can have its own volume attached and then once you start the cluster up any data sent to one node will automatically be replicated to the other nodes.

**Comment by elhe26** [comment]
> @elhe26 When you setup Typesense in [clustered mode](https://typesense.org/docs/guide/high-availability.html), Typesense will take care of replicating data between all the nodes in the cluster. So you do not need to share disks between multiple droplets / VMs. Each droplet / VM can have its own volume attached and then once you start the cluster up any data sent to one node will automatically be replicated to the other nodes. 

Wow. I didn't know that was possible.

"Client libraries will load balance reads and writes across all node... "; based on this, there's no need to use use load balancers. 


What I was thinking was to have a load balancer in front of the droplets, use subdomains on each droplet (upload1.example.com) to write data and one subdomain (search.example.com) connected to the load balancer to read data.

**Comment by jasonbosco** [comment]
> there's no need to use use load balancers

That's correct. Load balancers are not needed, but I know users who do use load balancers, especially when they want load balancing to happen on the server-side instead of the client-side. I'd say either approach work. We optimize for reducing operational overhead which is why we have client-side load balancing as an option.
