### ISSUE TITLE
One-way synonyms does't seem to work for me. Multi-way synonym works

### ISSUE THREAD

**Issue by dingusagar** [typesense/typesense#238]
## Description
One-way synonyms does't seem to work for me. Multi-way synonym works.
data in my collection : ['Bangalore', ...]
synonyms I added : ['Bengaluru', 'Banglore']
when I search 'Bengaluru', its not getting matched with any records.

I do not have these synonym words in any of the records in the collection. 

Another finding is when I tried the Multi-way synonym, it was working. Just wanted to know if there is any big difference in terms of performance between One-way synonym and Multi-way synonym. If not, I could just use the Multi-way synonym for my usecase.  Would love to get some insights into what is internally happening at a high level.

## Steps to reproduce

    synonym = {
        "root": 'Bangalore',
        "synonyms": ['Bengaluru', 'Banglore']
    }
 
client.collections[schema].synonyms.upsert(synonym_name, synonym)

## Expected Behavior
expected to match the record : 'Bangalore'

## Actual Behavior

Did not match with any records.

## Metadata

**Typsense Version**:
0.19.0

**OS**:
Ubuntu 20 LTS

**Comment by kishorenc** [comment]
@dingusagar The example you have given above is working as expected, since it's a one-way synonym mapping. Since you have set `Bangalore` as the root, only that will be resolved to records containing the other variations like `bengaluru`. 

As explained in the docs [here](https://typesense.org/docs/0.19.0/api/#synonyms), one-way synonyms should be used when you want only the `root` to be resolved as a synonym. For example, mapping `smart phone` (a generic term) to `Samsung Galaxy` and `Apple iPhone` will be helpful, but the reverse of that, i.e. returning records with the phrase `smart phone` for `apple iphone` search query is not.

In your case, since you want all the variations of `Bangalore` to match, it should be a multi-way synonym.

**Comment by dingusagar** [comment]
the smart phone example makes sense for one way synonym. 

I think i felt the docs about this to be little confusing.

this is from the [docs](https://typesense.org/docs/0.19.0/api/#synonyms) 
`One-way synonyms
Defining the words DEF and XYZ as one-way synonyms of ABC will cause searches for DEF or XYZ to return records containing ABC.`

here I interpreted this as 
synonym = {
    "root": 'ABC',
    "synonyms": ['DEF', 'XYZ']
}
so when I search 'DEF' or 'XYZ', I should get the records containing 'ABC'. 

Anyways thanks for clarifying.
