### ISSUE TITLE
concurrent users estimate

### ISSUE THREAD

**Issue by bnfd** [typesense/typesense#274]
How many concurrent users can a single typesense instance support without seriously degrading the search experience (sub 500ms response time)?
I understand this depends on the number of documents and the server's hardware.

I would be interested in knowing a (very) rough estimate for:
a. a server having 4 vCPUs, 8GB RAM and 1M documents. 
b. a server having 4 vCPUs, 16GB RAM and 1M documents. 

Has the team (or anyone else) done any testing on this front?

**Comment by jasonbosco** [comment]
Hi @bnfd, here are some reference benchmarks: https://github.com/typesense/typesense#benchmarks

- A dataset containing 2.2 Million recipes (recipe names and ingredients):
  - Took up about 900MB of RAM when indexed in Typesense
  - Took 3.6mins to index all 2.2M records
  - On a server with 4vCPUs, Typesense was able to handle a concurrency of 104 concurrent search queries per second, with an average search processing time of 11ms.
- A dataset containing 28 Million books (book titles, authors and categories):
  - Took up about 14GB of RAM when indexed in Typesense
  - Took 78mins to index all 28M records
  - On a server with 4vCPUs, Typesense was able to handle a concurrency of 46 concurrent search queries per second, with an average search processing time of 28ms.
- With a dataset containing 3 Million products (Amazon product data), Typesense was able to handle a throughput of 250 concurrent search queries per second on an 8-vCPU 3-node Highly Available Typesense cluster.

**Comment by bnfd** [comment]
Hi @jasonbosco, thanks for the reply!
What would happen if there were 100 concurrent search queries on the second example (books)? Would the remaining requests (beyond the initial 46) get ignored? Would all requests get denied (lost queries) or get served in FIFO order?

**Comment by jasonbosco** [comment]
The requests would get served in FIFO order by Typesense, as long as the OS is able to accept new TCP connections and CPU capacity is not saturated. Once either happen, then the OS itself might stop accepting new connections to protect itself, so clients would likely see timeouts at that point. Typesense itself doesn't reject connections - it will continue serving traffic as long hardware capacity is available.

**Comment by bnfd** [comment]
Thanks. 
What if I have multiple smaller indices? Instead of 1M records index, have 100 separate indices of 10K records each. Would that more or less result in a similar number of concurrent search queries or would it be completely different?

**Comment by jasonbosco** [comment]
Separating out data into smaller collections will definitely help improve concurrency, since we can parallelize more efficiently. 

10K per collection feels too small though. I'd recommend trying with 1M in 1 collection and if you need more concurrency, first try throwing more hardware (CPU) at it if possible. Then try splitting it into two collections of 500K each, and then splitting into 4 of 250K each, etc and seeing what works best.

**Comment by bnfd** [comment]
Actually I meant something else. Supposing there's an app allowing users to upload their own collections (size of each individual collection ranges from 10k to 50k records), how many instances of typesense would need to be deployed to be servicing 100 concurrent queries (i.e. 100 different users using the app)?
user1 would do queries on collection1 only, user2 would do queries on collection2 only and so on.

**Comment by jasonbosco** [comment]
I think 4vCPUs should be sufficient to handle that volume. That said, the shape of the dataset and schema also play into concurrency, so it's best to benchmark with a representative dataset to get the exact thresholds.

Separately, I'd recommend scaling vertically by adding more RAM / vCPU before scaling horizontally with multiple clusters, especially since the former is easier to do compared to the latter.

**Comment by YassKhazzan** [comment]
hello all, i want to replace my redis database that im using for api keys validations with typesense. i only have one collection (users) and this collection have 5 fields (usage: int,email : string, api-key : string , limit : int) , i have 7000 users and i run up to 10000 concurrent api call, so i will need 10000 concurrent calls for typesense. how much CPU will i need ? since the data itself is just 7000 entries
