### ISSUE TITLE
Not getting exact match

### ISSUE THREAD

**Issue by copydepo** [typesense/typesense#278]
## Description
Searching won't give me the result with exact match in text.

## Steps to reproduce
I have a collection of products. I am querying by the following fields: title, slug 

Then I type "m5799" to input field, which is an exact match in one of my products.

## Expected Behavior
Get result for a product called: Epson WorkForce Pro WF-M5799DWF Mono Mfp

## Actual Behavior
Receiving the following results instead:
-Szerviztáska / 15799/ 
-Oki ML5790 Mátrix Nyomtató
-Oki ML5791 A3 Mátrix Nyomtató

## Metadata

**Typsense Version**: 0.20

**OS**: Linux Ubuntu 18.04

**Comment by kishorenc** [comment]
@copydepo We've address this issue as part of https://github.com/typesense/typesense/issues/191

Please use this release candidate DEB for testing the change: https://dl.typesense.org/releases/0.21.0.rc7/typesense-server-0.21.0.rc7-amd64.deb

**Comment by copydepo** [comment]
Hi, thanks for fast response. I updated the package, still not getting good results :(

> @copydepo We've address this issue as part of #191
> 
> Please use this release candidate DEB for testing the change: https://dl.typesense.org/releases/0.21.0.rc7/typesense-server-0.21.0.rc7-amd64.deb

**Comment by kishorenc** [comment]
Can you give me a small dataset and a sample query that will exhibit the issue? I will then be able to figure out what could be going wrong.

**Comment by kishorenc** [comment]
@copydepo Sorry I just noticed that you had an example in the first comment. I will explain why this query is not fetching expected results.

When Typesense indexes the token "WF-M5799DWF", it will index it as "WFM5799DWF" -- therefore the word "m5799" goes into the middle of the token. This is because Typesense's tokenizer will remove all special characters before indexing. If you don't want this behavior for hyphens, please split the text before indexing, so index as "WF M5799DWF" and you will get expected results.

**Comment by copydepo** [comment]
> @copydepo Sorry I just noticed that you had an example in the first comment. I will explain why this query is not fetching expected results.
> 
> When Typesense indexes the token "WF-M5799DWF", it will index it as "WFM5799DWF" -- therefore the word "m5799" goes into the middle of the token. This is because Typesense's tokenizer will remove all special characters before indexing. If you don't want this behavior for hyphens, please split the text before indexing, so index as "WF M5799DWF" and you will get expected results.

If I understand it correctly, so if our clients search for the keyword "5799" they will never get WFM5799DWF result.

Then we won't be able to actually use this otherwise awesome library :(

**Comment by copydepo** [comment]
Hi thanks for your reply!

I get the idea behind splitting the words, and it works for the keyword "m5799" for now. But our case is there is this keyword: M5799DWF and our clients search for it a lot of times like simply by typing "5799" so the numbers only. Is there any way so we can handle that as well?

Thanks in advance!

**Comment by kishorenc** [comment]
@copydepo Matching on model numbers via fuzzy search resolution is tricky because if you had tokens "m5799" and "i5799", technically both are within edit distance of 1 from the query term "5799" but they could be very different products. 

One way our customers deal with this ambiguity is by indexing model variations in a separate field and query those fields as well. So you can add a field like this: 

```
"model_variants": ["M5799DWF", "5799", "M5799"]
```

This allows the token to be matched across different variations of how people might type model number. 

We've also recently [added a feature](https://github.com/typesense/typesense/issues/262#issuecomment-844631342) that allows you to disable fuzzy search for a specific field: so you should disable fuzzy search on the `model_variants` field since we don't want other similar model numbers to match based on typo correction mechanism.

Finally, how to easily generate those model number variations? It can be done programatically by applying a few heuristics. Model numbers are typically strings that fit into a few rules:

1. Has a mix of number and upper case characters, e.g. `M5799DWF`
2. Might have 2/3 upper case characters followed by a number, e.g. `YK 7212`
3. Might be a hypen separated word containing numbers on both sides, e.g. `700-695`

Using this you can easily identify a model number token from the title and index it as a separate field with programatically constructed variations. This will give pretty amazing results.
