### ISSUE TITLE
Letsencrypt ssl certificate works for clients but fails for server side scripting

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense#306]
I am using typesense with php  and i have secured with  with letsencrypt

and i am getting this error  when i try conencting to it from the server side 

```
Http\Client\Exception\NetworkException
SSL peer certificate or SSH remote key was not OK for "https://api.example:8108/collections".
↵
Caused by: Symfony\Component\HttpClient\Exception\TransportException
SSL peer certificate or SSH remote key was not OK for "https://api.example:8108/collections".
in /var/www/html/myhotel/vendor/symfony/http-client/Chunk/ErrorChunk.php at line 65

↵
Caused by: Symfony\Component\HttpClient\Exception\TransportException
SSL peer certificate or SSH remote key was not OK for "https://api.example:8108/collections".
in /var/www/html/myhotel/vendor/symfony/http-client/Response/CurlResponse.php at line 317
```

This is my typesense config

```
; Typesense Configuration

[server]

api-address = api.example
api-port = 8108
data-dir = /var/lib/typesense
api-key = 636367gdgdgdggd
log-dir = /var/log/typesense
enable-cors = true
ssl-certificate = /etc/letsencrypt/live/api.example/cert.pem
ssl-certificate-key = /etc/letsencrypt/live/api.example/privkey.pem
```

I can connect and read a collection from vue js on the client side however when i try executing a command, i get the error.This error does not register on the logs.

The http client is as exactly as on the docs https://github.com/typesense/typesense-php/blob/master/examples/collection_operations.php

What could be the issue?

I am using this version `typesense-server-0.21.0.rc7-amd64.deb`

**Comment by britisharmy** [comment]
I haven't found the exact solution but doing it in curl by disabling ssl verification works

```
  $headers = array(
				'Content-Type:application/json',
				'X-TYPESENSE-API-KEY: gdhdh777....'
			 );
			 $random = mt_rand();
			 $sn = rand(6,900);
			$payload = array(
			"id" => "$random",
			"name" => "$random"
		     );
		$url = 'https://example.com:8108/collections/mh_props/documents';
		$process = curl_init($url);
		curl_setopt($process, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($process, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($process, CURLOPT_HEADER, 1);
		curl_setopt($process, CURLOPT_TIMEOUT, 30);
		curl_setopt($process, CURLOPT_POST, 1);
		curl_setopt($process, CURLOPT_POSTFIELDS, json_encode($payload));
		curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	
		$return = curl_exec($process);
		$info = curl_getinfo($process);
		curl_close($process);
		echo "<pre>";
		print_r($return);  
        echo "</pre>"; 
```

but this isn't encouraged. More on this here https://stackoverflow.com/a/29443322/492293

I just want to try our various features so this solution works until a permanent solution is found.

**Comment by kishorenc** [comment]
Can you try using the full certificate chain in `cert.pem`? It is possible that your cert does not have intermediate certs so that might be tripping up the client. Read more here: https://support.dnsimple.com/articles/what-is-ssl-certificate-chain/

**Comment by britisharmy** [comment]
I shall have a deeper look into and see if that was indeed the case. My ssl seller mentioned the same thing.

**Comment by panoet** [comment]
I am facing same issue after installing new certificate, 

```
; Typesense Configuration

[server]

api-address = 0.0.0.0
api-port = 8108
data-dir = /var/lib/typesense
api-key = ---some api key---
log-dir = /var/log/typesense
enable-cors = true
ssl-certificate = /var/lib/typesense/ssl/bundle.crt
ssl-certificate-key = /var/lib/typesense/ssl/private.key
```

Intermediate and root has been packed to bundle.crt. But if I access the server from it own server using localhost, I got
**curl: (52) Empty reply from server**

**Comment by 4i-helpynet** [comment]
Hi all

LetsEncrypt certs
My server conf is:

```
; Typesense Configuration

[server]

data-dir = /var/lib/typesense
api-key = [apikey]
log-dir = /var/log/typesense
enable-cors = true
cors-domains = [domainlist]
ssl-certificate = /etc/letsencrypt/live/[server]/fullchain.pem
ssl-certificate-key = /etc/letsencrypt/live/[server]/privkey.pem
```
1:
**curl http://localhost:8108/health**
curl: (52) Empty reply from server

2:
**curl https://localhost:8108/health**
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

3:
**curl https://localhost:8108/health --insecure**
{"ok":true}

Seems to be insecure local curl call working, anything else in local linux server get back empty response

Should it work on local servercall with plain http instead https, or I'm wrong?

**Comment by jasonbosco** [comment]
> Should it work on local servercall with plain http instead https, or I'm wrong?

Once you configure `ssl-certificate` and `ssl-certificate-key` in Typesense, it will only accept HTTP traffic on the API port.

> https://localhost:8108/health

I don't think localhost domain is supported by LetsEncrypt certificates: https://letsencrypt.org/docs/certificates-for-localhost/

which is why it's complaining about an invalid certificate
