### ISSUE TITLE
Wrong facete distribution

### ISSUE THREAD

**Issue by interlark** [typesense/typesense#319]
## Description

I checked out your [showcase](https://songs-search.typesense.org/?s%5Bquery%5D=kork&s%5BrefinementList%5D%5Bprimary_artist_name%5D%5B0%5D=Viikate) and seems like facete `Viikate` shows `3 results`, but when you click it, it shows much more than 3 with query `'kork'`. It happens on any facete.

## Steps to reproduce

Click the link from the above and behold yourself.

## Expected Behavior

Facete should give you actual information, in this particular case 56.

## Actual Behavior

![image](https://user-images.githubusercontent.com/20641837/126365060-88f19fab-f950-4758-976b-9176ca21217d.png)

**Comment by interlark** [comment]
Same thing with e-commerce showcase
![image](https://user-images.githubusercontent.com/20641837/126367232-728faf1a-31b1-4586-98d5-ee84c592bbc8.png)

**Comment by kishorenc** [comment]
@interlark 👋 Thank you so much for taking the time to report this glitch. It's not exactly an error in the calculation of facet count. It's due to an interplay between the various queries used to populate the different widgets in the UI and the slightly inconsistent manner of typo correction on small data sets.

The good news is that we recently fixed this inconsistency as part of [another reported issue](https://github.com/typesense/typesense/issues/315) -- if you are running the ecommerce example locally, can you please try running it against `typesense/typesense:0.22.0.rc2`?

We will be upgrading our demo backend to use this version soon.

**Comment by interlark** [comment]
I tried `0.22.0.rc2` with `showcase-ecommerce-store`, same thing.
![image](https://user-images.githubusercontent.com/20641837/126510319-1e7571f0-b447-4c35-a002-cb528c26ca65.png)

**Comment by kishorenc** [comment]
Indeed. We've to make some adjustments to the instantsearch adapter to take care of this. I will update this thread when we have that ready.

**Comment by adrienpicard** [comment]
@kishorenc Great to hear a fix will soon be available. Is there an RC2 Linux build I could try somewhere? Thanks!

**Comment by kishorenc** [comment]
@adrienpicard Here's a [DEB build](https://dl.typesense.org/releases/0.22.0.rc2/typesense-server-0.22.0.rc2-amd64.deb).

**Comment by adrienpicard** [comment]
@kishorenc Works like a charm thank you!

**Comment by jasonbosco** [comment]
Released in v0.22
