### ISSUE TITLE
Logs use case - Alternative to elasticsearch

### ISSUE THREAD

**Issue by prabhatsharma** [typesense/typesense#320]
Primary index location for typesense is RAM and not disk which means that typesense is perfectly fit for fast search in applications but not really for large scale log search, a primary use case for elasticsearch.

Is this right understanding?

**Comment by jasonbosco** [comment]
Typesense does store the index in RAM, unlike Elasticsearch, which is what makes Typesense fast. 

Whether you want to use Typesense for log search (or not) is a tradeoff consideration between speed of search vs cost (of RAM). Technically, if your log lines are / can be JSON-structured, then they can be indexed, filtered, faceted, grouped, sorted, etc with Typesense and used for visualization, just like any other JSON data. 

Now, the key technical limit to be aware of is that, you're limited by the amount of RAM you're able to provision on a single node. AWS for eg offers up to 24TB of RAM on a single node. Beyond that you'd have to shard the data between multiple Typesense clusters on the application side. 

Whether paying for RAM, to get fast search & filtering on logs is worth it, is a business decision. 

FWIW, among the pool of users who I have contact with, I know at least one user who is using Typesense for structured log search / filtering, because speed is important to them - they're building an application for their customers to parse through specialized logs.
