### ISSUE TITLE
Duplicate fields can get into schemas/documents

### ISSUE THREAD

**Issue by morphine00** [typesense/typesense#328]
## Description

Duplicate fields can get into schemas/documents, at least using the Python API.

## Steps to reproduce

Create documents in a collection with the same field appearing more than once.

## Expected Behavior

An error saying that the field already exists.

## Actual Behavior

Duplicate (or triplicate, etc) fields in both the document and schema.

## Metadata

**Typsense Version**: 0.21.0

**OS**: n/a

**Comment by unclescooby** [comment]
I too am curious why duplicate schema fields are allowed. In a previous typesense version (0.20?) only duplicate regex fields did not produce an error. In 0.21 both explicit and regex fields produce no errors.

I have found that, at least for explicit fields, the first name entry in the schema locks in the fieldname, ie. the second entry does not override the first one.

For example, based on the schema fields from the 'create a collection' API docs, the following schema modification produces no indexing error:

`{"name": "company_name", "type": "string" },
 {"name": "company_name", "type": "string[]" },`

Whereas the following produces an error Field `company_name` must be an array.

`{"name": "company_name", "type": "string" },
 {"name": "company_name", "type": "string[]" },`

Re duplicate fields in documents: that's probably because the json document data gets parsed into an array with key:value pairs (like PHP associative array, javascript object, etc). The duplicate simply overwrites the first. Try indexing a document with the following:

` 'company_name'  => 'Stark Industries',
   'company_name'  => 'Stark Industriez',`

**Comment by kishorenc** [comment]
This is certainly an oversight and should be handled. Collection creation should not be allowed if they contain duplicate field names.
