### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [typesense/typesense#33]
Would you like to [wrap any pointer variables](https://github.com/typesense/typesense/blob/36a022a89251348051571016b62ce596afc6ceee/src/array.cpp#L44 "Update candidate: array::remove_index()") with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by kishorenc** [comment]
@elfring I'm generally a fan of smart pointers as raw pointers can become hard to manage. In this case, however I refrained from wrapping for a couple of reasons:

1. Parts of Typesense initially began as a C project, and still uses some C-style code so those parts just used raw pointers.
2. To a lesser extent, I was worried about the performance overhead introduced (admittedly this is more of a case for `shared_ptr` than `unique_ptr`) in hot loops. I did do some initial benchmarks where I saw some serious degradation. 

In the end, instead of adopting a mixed style, just ended up not using it anywhere. As a form of mitigating leaks, we have an integration test suite (which is not part of this repo) that's run under Valgrind.

**Comment by elfring** [comment]
How do you think about to [improve the implementation of the member function “array::remove_index”](https://github.com/typesense/typesense/blob/36a022a89251348051571016b62ce596afc6ceee/src/array.cpp#L44 "Update candidate: array::remove_index()") (for example)?

**Comment by kishorenc** [comment]
@elfring I'm sorry for going silent on this thread. We're comfortable with using raw pointers as of today, given the heavy interoperability with the C libraries we're using. We might relook this at future. Thanks for bringing this up though!
