### ISSUE TITLE
A filter_by clause is not returning all matched documents

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense#349]
## Description
A search query without a filter_by returns X documents, all with a number field `nsfw` set to `0`. The same exact query with a `filter_by=nsfw:0` returns fewer documents. Why?

## Steps to reproduce
Download tar/gz of database (300MB, sorry): https://telparia.com/typesense_data.tar.gz

Extract `typesense_data.tar.gz` into a `data` dir

Start the server with `typesense-server --api-key=GS8aW2LIdpEWhM69Ijir0y5QeiomZfI --data-dir=data`

Run this query and pipe to `jq` (or process the JSON how you'd like)
`curl -H "X-TYPESENSE-API-KEY: GS8aW2LIdpEWhM69Ijir0y5QeiomZfI" "http://localhost:8108/collections/twig/documents/search?query_by=filename&prefix=true&include_fields=filename,nsfw&num_typos=0&typo_tokens_threshold=0&drop_tokens_threshold=0&per_page=250&q=smus" | jq '.hits[].document'`

It returns a bunch of documents, all with `nsfw` field set to `0`
Note that several of the returned documents have a `filename` field set to `smus.h`

Now run the same exact query, but add a `filter_by=nsfw:0`
`curl -H "X-TYPESENSE-API-KEY: GS8aW2LIdpEWhM69Ijir0y5QeiomZfI" "http://localhost:8108/collections/twig/documents/search?query_by=filename&prefix=true&include_fields=filename,nsfw&num_typos=0&typo_tokens_threshold=0&drop_tokens_threshold=0&per_page=250&q=smus&filter_by=nsfw:0" | jq '.hits[].document'`

## Expected Behavior
I'd expect the second query would yield the same exact documents, since all the results from the first query have `nfsw` set to `0`, so they should all match the second query with the added `filter_by` clause.

## Actual Behavior
Instead the second query returns fewer items, in particular all the `filename : smus.h` documents have disappeared.

What's going on?

Am I not using typesense correctly?

## Metadata
**Typsense Version**: 0.21.0
**OS**: Gentoo Linux x86_64 (Kernel 5.13.1)

**Comment by kishorenc** [comment]
@Sembiance 

Thank you for the data dump. I downloaded, ran and was able to reproduce the behavior you noticed on `0.21.0`, but this works fine on the latest RC build:

 ```
typesense/typesense:0.22.0.rcu4
```

Can you please try against that? We recently addressed an edge case with small-prefix iteration which might have caused this.

**Comment by kishorenc** [comment]
@Sembiance One additional piece of information: 

Very small prefixes (2 or 3 char prefixes) can sometimes match hundreds/thousands of words. In such a case, Typesense _might_ not be exhaustive in going through every one of those words, in the interest of relevancy and performance. So this might cause some record/count mismatches when you compare two queries with/without filtering. This is because, when filters are added, the candidate words that match a prefix can vary, so this can change what records are actually fetched. 

To address this issue, in the `0.22.0` RC builds, we have added a `?exhaustive_search=true` flag  that ensures that Typesense always looks at all prefixes to be exhaustive. Performance impact should be negligible unless the token matches several thousand words on a several million record dataset. I recommend you to use this flag.

**Comment by Sembiance** [comment]
@kishorenc Does the `0.22.0-rc` branch source code contain the latest `rcu4` build you speak of if I compile that?

Otherwise, is the `0.22.0.rcu4` source code available anywhere?

Or where else can I get the `0.22.0.rcu4` compiled binary? (not docker)

**Comment by kishorenc** [comment]
Please find the binary [here](https://dl.typesense.org/releases/0.22.0.rcu4/typesense-server-0.22.0.rcu4-linux-amd64.tar.gz).

**Comment by Sembiance** [comment]
@kishorenc Cool, thanks for the link, I'll use that. For future reference though, is the source for the very latest versions such as `rcu4` not available on github?

**Comment by kishorenc** [comment]
Yes, certainly. The latest changes are being developed on the `postings-refactor-integration` branch, which began as a feature branch, but I've continued working on it for further 0.22.0 changes as well.

**Comment by Sembiance** [comment]
Thanks for the info! I'll check it out, but it might be some time. Will close the issue, as it sounds like it's fixed. Thanks!
