### ISSUE TITLE
search-only-api-key does not work with 0.8.0 docker image

### ISSUE THREAD

**Issue by janimo** [typesense/typesense#38]

**Comment by kishorenc** [comment]
@janimo I just tried and it's working fine. Can you please post the commands you ran? Here's how I started Docker:

```
docker run -p 8108:8108 -v/tmp/typesense-data:/data typesense/typesense:0.8.0 \
--data-dir /data --api-key=abcd --search-only-api-key=1234
```

And when you query, you will have to set the `x-typesense-api-key` header to the search-only-api-key, i.e. `1234`.

If this is still not working, please post the code/curl commands you are using so that we can investigate further.

**Comment by kishorenc** [comment]
We synced up offline about this. The confusion was around which end-points `search-only-api-key` will allow access to - it only allows access to the `/collections/collection_name/documents/search` end-point.
