### ISSUE TITLE
Cannot retrieve document with space in id

### ISSUE THREAD

**Issue by gaomengen** [typesense/typesense#483]
## Description

If my document id has space in it and I want to use Retrieve a document endpoint to get that document, how should I escape the space in the url? I tried %20 and + but both returned not found. Is having space inside document id a bad practice? 

## Steps to reproduce

Create a document with space in it and use document retrieve to get the document by id 

## Expected Behavior

Hope to find the document by ID

## Actual Behavior

It will not find anything with that id, even though the document with that id exists

## Metadata

**Typsense Version**:
latest

**OS**:
Typesense cloud

**Comment by kishorenc** [comment]
@gaomengen We don't support retrieving documents with a space in the ID because it's not a common practise. Identifiers are generally numeric or alphanumeric characters. If we tried to parse a space encoded string, that might conflict with actual IDs that use the encoded characters as part of their ID.
