### ISSUE TITLE
Filter out items with empty arrays as value?

### ISSUE THREAD

**Issue by Apeli** [typesense/typesense#495]
## Description

We have a event database with location data for events, as Array (lat, lng). Some events have empty location data (0,0). Can I filter out those events somehow?

location:!=(0,0) doesn't work, throws error:   Value of filter field `location`: must be in the `(-44.50, 170.29, 0.75 km)` or (56.33, -65.97, 23.82, -127.82) format.

## Metadata

**Typsense Version**: 0.22.1

**OS**: OSX

**Comment by kishorenc** [comment]
@Apeli 

Since Typesense uses an inverted index of `value -> document_id`, when a particular is empty, we just don't store a value in the index. So, we are unable to locate records which are empty.

One way to handle this is to pick a location in a far-off region (maybe in Antarctica) and use that to represent the "empty" value.
