### ISSUE TITLE
OR query mode 

### ISSUE THREAD

**Issue by dav1d992** [typesense/typesense#532]
## Description

I have a case where I'd like to search for multiple query tokens in a single collection like: 

```
let searchRequests = {
  'searches': [
    {
      'collection': 'products',
      'q': 'shoe hat dress perfume',
    }
  ]
}
```
each token contains results if I query them individually and also if I query two tokens like so:  `'q': 'shoe hat',`. 

Is there a way to allow for more than two query items? 

## Expected Behavior

I expect to have results returned based on my query tokens `'shoe hat dress perfume',` or in other words an `OR` query mode: 
```
{
  "results": [
    {
      "facet_counts": [],
      "found": 100,
      "hits": [  
        ...
    } 
  ]
} 
```

## Actual Behavior

The actual behavior is that nothing is found: 
```
{
  "results": [
    {
      "facet_counts": [],
      "found": 0,
      "hits": [  
        ...
    } 
  ]
} 
```

## Metadata

**Typesense Version**: 0.22.0

**Comment by kishorenc** [comment]
@dav1d992 

Let me explain how Typesense will attempt to search for the query `shoe hat dress perfume`.

1. It will first try to look for documents that contain ALL tokens in the query.
2. If no such documents are found, it will try to do typo variations of the tokens in the query.
3. If that also fails to produce results, it will try to drop the words in the query from right to left, and then left to right, one by one, looking for results to be found. 

With the dropping of words in 3) Typesense already does a form of `OR`. But we don't have plan to support strict ORs because that tend to produce a lot of noise, slow and is not useful in practical scenarios.
