### ISSUE TITLE
Typesense for Email search and In Depth architecture of Typesense

### ISSUE THREAD

**Issue by luvk1412** [typesense/typesense#547]
I am evaluating Typesense for using it in an Email product but i had few technical questions which I needed answer to and I am unable to find docs/resources which explain in-depth working around architecture of typesense. It would be great if such resources are there, and if they can be linked to here. I did found somewhere in docs that [ART](https://db.in.tum.de/~leis/papers/ART.pdf) is being used underneath and I do plan to go through the paper but i am not sure of additional overheads typsense would have over it.

I am also listing down my questions here. In case if someone from the team can answer, it would be really helpful.
- How are Updates and Deletes In Typesense handled ? Emails are often deleted or their attributes can often change(and the scale increases more when these operations are done in bulk), 
  - so I need to know how deletes/updates are handled
  - how would they impact the performance. 
  - Are deleted documents persisted in memory and then lazily deleted ? in case yes then how much time does it takes for deleted documents to purge, can we force purge ? how would force purge impact performance ?
  - I have found in general that search solutions face difficulty in doing deletes/updates. For example Elastic search suffers through performance when deletes are introduced due to how Lucene handle deletes as mentioned [here](https://www.elastic.co/blog/lucenes-handling-of-deleted-documents), hence I have similar concerns for typesense as well.
- What is the limit on number of indexes/collections one can have in a single cluster (assuming size of each index will be small(10-20Mb lets say)), How would it impact the system if we have large number of indexes/collections.
- Way I am thinking around implementing it is having one index/collection per user. So i am thinking if there is a way to export your collection/index into a file and then later reimport it again. Please note that i am not talking about exporting/importing data here for which i saw the api's in your docs, I am talking about exporting/importing the whole index data structure so that we don't have to recreate it. I plan to store those exports in S3 or some other object storage and load it when required. I know this will make search a bit slower but that is fine with me.

**Comment by kishorenc** [comment]
👋 

**Updates and Deletes**

- Typesense stores the raw JSON documents on-disk, while the inverted index and the other auxiliary search datastructures are stored in-memory. When the server is restarted the in-memory datastructures are re-created from the raw disk JSON documents.
- During an update operation we diff the contents of the document uploaded with the one stored on disk. Fields that don't change are just skipped. Care has been taken to ensure that updates don't face performance issues that you typically see with other search engines (as you've mentioned). Since we only use in-memory datastructures, are are able to support amortized constant-time updates and deletes. The 0.23 RC version has done more work here, so I would recommend using that for any testing.

**Collection limits**

- We have seen people using north of 100K collections on the 0.22 version. The overheads are fairly minimal so you should be able to scale linearly if you use a beefy box and configure it to have enough resources like ulimit open files etc.
- Having said that, instead of having 1 collection per user, I would recommend having a large number of fixed collections, say 10,000 collections and then hashing several users into a collection ID via `user_id % 10000` -- this way you control the fan-out. You can also use some form of consistent hashing to make future rehashes easier.

**Exporting index**

We don't have a way to do this. Since all the datastructures are in-memory and they are fairly specialized, there is no way to dump them onto disk without custom serialization logic, which will be as good as exporting the data and importing fresh.

**Comment by luvk1412** [comment]
@kishorenc thanks for replying.

> which will be as good as exporting the data and importing fresh

Would this mean that time to create the index datastructure from raw data is similar to time it would take to load that raw data into memory from disk? eventually meaning that time taken to index a document is a CONSTANT ?

**Comment by kishorenc** [comment]
If you are talking about time to index via the import API vs creating the index datastructures from disk during a restart of the server, yes they tend to about the same but the reading from disk is faster because we can make some additional parallelization vs consuming sequentially from the API.

Unlike other search engines like Elasticsearch, Typesense does not persist the index datastructures on-disk. This gives us a lot of benefits in terms of flexibility, read and write performance, but the downside is that you can't export and restore these data structures as-they-are from memory to disk and back to memory.
