### ISSUE TITLE
Query string exceeds max allowed length of 4000

### ISSUE THREAD

**Issue by alvinchan88** [typesense/typesense#558]
Great work on Typesense guys!  Ran into this problem.  Anyway to work around this??

## Description

Tried to perform a query with a long search parameters. Specifically, filter by a long array with user ids (uid).   

## Steps to reproduce
    Using node.js

    let searchParameters = {
        'q'         : 'skate',
        'query_by'  : 'title',
        'filter_by' : 'uid:=' +  array.users + '\'',
      }
      
    client.collections('posts')
        .documents()
        .search(searchParameters)
        .then(function (searchResults) {
          console.log('Search Results')
          console.log(searchResults)
        })

## Expected Behavior

Return search result

## Actual Behavior

(node:65540) UnhandledPromiseRejectionWarning: Error: Request failed with HTTP code 400 | Server said: Query string exceeds max allowed length of 4000. Use the /multi_search end-point for larger payloads.

## Metadata

**Typsense Version**: 0.22.2

**OS**:  running docker image on mac

**Comment by jasonbosco** [comment]
We limit GET parameter size for security reasons. So you instead want to use the [multi_search](https://typesense.org/docs/0.22.2/api/documents.html#federated-multi-search) endpoint (even if you only send a single search request within a multi_search) which uses POST and doesn't have a limitation on payload size.

**Comment by alvinchan88** [comment]
Perfect...thx for answering so quickly Jason!  Recommend mentioning this in the docs.

**Comment by hashimsayed0** [comment]
> We limit GET parameter size for security reasons. So you instead want to use the [multi_search](https://typesense.org/docs/0.22.2/api/documents.html#federated-multi-search) endpoint (even if you only send a single search request within a multi_search) which uses POST and doesn't have a limitation on payload size.

Hi @jasonbosco 

I've run into an issue where I'm using limit, sort_by and filter_by in a query. The parameter size exceeds 4000 characters due to a long filter_by parameter. I'm unable to sort and limit the retrieved documents together (amongst all batches of documents) when using multi_search. With multi_search, I get multiple batches of documents, one for each request and each batch sorted among themselves. Is there a way I can overcome this issue, either by being able to increase the parameter size from 4000 or by any other method?

Thank you

**Comment by jasonbosco** [comment]
@hashimsayed0 I think I understand what you're saying, but I'm not sure I understand how it's related to the 4000 query parameter limit of the GET /search endpoint. Because the `POST /multi_search` endpoint does not have that limitation and it shouldn't throw any errors related to this. Could you elaborate on that? 

In any case, to answer your question about how to sort documents across the different batches of results inside the multi_search request using this new feature: https://github.com/typesense/typesense/issues/381#issuecomment-2555842091

**Comment by hashimsayed0** [comment]
@jasonbosco Apologies for the misunderstanding. I ran into the 4000 query error in a normal query. I'll have a look into the comment you shared. Thank you

**Comment by hashimsayed0** [comment]
Hi @jasonbosco 

The issue I had with normal queries was specifically with filtering out documents based on their ids. I have 2 scenarios.

1. In this scenario, I need to make sure the id is one of a long list I pass in, ie. `'filter_by': 'id:=[id1, id2, id3, ....]'`. I could solve for this scenario by dividing this long list into multiple shorter lists and using union in multi_search. 
2. In this scenario, I need to make sure the id is NOT one of a long list passed in, ie. `'filter_by': 'id:!=[id1, id2, id3, ....]'`. Dividing this long list into shorter lists and using union with multi_search does not work in this instance as an individual query could retrieve documents that the other query filters out.

Could you suggest a fix for this? Thank you.
