### ISSUE TITLE
Search result not highlighted for the infix search

### ISSUE THREAD

**Issue by versitastorebdpreprd** [typesense/typesense#559]
## Description

The search result from the infix is not highlighted even search results found

## Steps to reproduce
Actual text context `សម្លាប់ ៩៩,៩% នៃមេរោគ។ ទុកឱ្យដៃមានអារម្មណ៍ទន់។ មិនត្រូវការទឹក។ គ្មានក្លិនក្រអូប។ ផលិតនៅកម្ពុជាជាមួយនឹងបច្ចេកវិទ្យានិងស្តង់ដារពីប្រទេសកូរ៉េ។`

 Here is the infix search for `ឱ្យដៃមានអារម` which is the infix with `query_by: item.description.kh && infix: fallback`
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/100656877/160055758-5a7bb37c-a56c-432a-bcd6-116c3aca2edb.png">

 Here is the infix search for `ទុកឱ្យដៃមាន` which is the prefix with `query_by: item.description.kh && infix: fallback`
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/100656877/160056022-c90a490c-b919-4cd7-9997-a0a590761b31.png">

## Expected Behavior

It should highlight anything the search result found and only the highlight the query not the whole phrase

## Metadata

**Typsense Version**: v0.23.0.rc49

**OS**: Mac 12.3

**Comment by kishorenc** [comment]
@versitastorebdpreprd 

I looked into this issue. The infix search feature is not meant for searching on long text strings. It's primarily meant for short strings like model numbers, email, phone numbers etc. Since infix search highlighting requires checking each word for infix match, we limit highlighting to the first 100 bytes of each field value for performance reasons. 

In this particular case, it looks like the text is not being being properly tokenized? Is that why you are relying on infix search?

**Comment by vichet16** [comment]
Thanks for your response

1. `ឱ្យដៃមានអារម` is not a long text string, I think it also not work even if it's only `ឱ្យដៃ`. Because it seems to me like it only highlight the prefix search results. Or by the long text string you refer to something else then please correct me
2. For it to highlight may be expensive but from user prospective, it's just that the result should be highlight since there're results and the highlight is enabled here

**Comment by kishorenc** [comment]
When I mean by "long text strings" I mean the entire field length, and not individual words that are to be highlighted.

**Comment by kishorenc** [comment]
> I have a text context field in between 15 ~ 30 alphabet characters each, but the infix search seems not working properly.

Please provide a reproduceable snippet so I can take a look.

**Comment by khaishin1999** [comment]
> > I have a text context field in between 15 ~ 30 alphabet characters each, but the infix search seems not working properly.
> 
> Please provide a reproduceable snippet so I can take a look.

Sorry that I do not have the backend code with me at this moment. But I can show it to you through the screenshot below.

_When I search "ck", the infix search seems working._
<img width="357" alt="image" src="https://user-images.githubusercontent.com/109172845/179169443-7bdfaf3d-cf62-462c-b6d8-705d49e10d7e.png">

_But somehow when I search "ckM", it show zero result._ 
![image](https://user-images.githubusercontent.com/109172845/179170111-3e19490d-f9cb-40da-9eca-6a8fb21d66af.png)

**Comment by kishorenc** [comment]
But none of the policy names in the screenshot have the sub string "ckM" -- that's why it's not matching. In any case, I can't debug unless you can provide a reproduceable example using one of our clients by indexing a document which you expect to match and showing the query where it does not match.

**Comment by khaishin1999** [comment]
In the data structure, we have added:
`{"name": "policy", "type": "string", "infix": true }`

And in typesense instantsearch adapter, we have put:
`queryBy: "..., policy, ...",`
`infix: "..., always, ...",`
`query: "*"`

Before search, we can see there is a policy call "CheckMultiplePVSCSI"
![image](https://user-images.githubusercontent.com/109172845/179485799-1d268c20-bc8b-44b3-995c-7bb414948307.png)

But after I type "Multiple" or "Multi" in the searchbox, it shows no result.
![image](https://user-images.githubusercontent.com/109172845/179485966-46eb5064-6d4b-46e3-88f1-c54909461544.png)

**Comment by kishorenc** [comment]
Since we don't have access to this UI, unless you can showcase the issue as a stand-alone example that we can run, it will be difficult for us to figure out what's going wrong here.

**Comment by khaishin1999** [comment]
Hi @kishorenc, I realized something about the exact problem I faced on this infix search issue.

 I cannot say the infix search is not working fully, it's just that I think it might has some relationship with prefix search.
 
 I realized that if another column that has the same strings with the column we want to do the **infix search**, it will go for prefix search for that first column and infix search result does not come out after that even if we type exactly strings for the infix data searching.
 
 For example, below are the dataset in the table:-
| First Column  | Second Column |
| --- | --- |
| Apple  | CarrotMilkJuice  |
| Orange  | PineAppleJuice  |

- When we typed "Apple" in the searchbox, both results will appear.

| First Column  | Second Column |
| --- | --- |
| _Apple_  | CarrotMilkJuice  |
| Orange  | _PineAppleJuice_  |

- However, if we continue typed "AppleJuice", we will get no result.

| First Column  | Second Column |
| --- | --- |
| - | - | 

<sub> ~> **_No result is found._** </sub>

Can you please advise on this issue? Thank you very much...

**Comment by khaishin1999** [comment]
#693
