### ISSUE TITLE
How to make it distributed?

### ISSUE THREAD

**Issue by melovv** [typesense/typesense#57]
## Description

I'd like to improve the number of queries per second by having a distributed system using round-robin. As far as I understood from your guide, the read replica is used only if there is a timeout. However, I'd like to have the queries passed to the next free read replica automatically. Then, if the query fails by timeout, it is passed to the next free replica as well.

## Expected Behavior

An example is below.

1. A master node knows 3 read replicas. The master has a queue. All Replicas are available.
2. Query A arrives and is pushed into the queue. 
3. The master sends A to Replica 1 and waits for the answer or the timeout.
4. Query B arrives and is pushed into the queue. 
5. The master sends B to Replica 2 and waits for the answer or the timeout.
6. Replica 2 answers and the master returns the result to the user. Now the master knows Replica 2 is free.
7. Replica 1 fails. The master now sends A to the next free Replica. Replica 1 should be marked as unavailable?
8. Query C arrives and is pushed into the queue. 
9. The master sends C to the next free Replica (3 ?)  and waits for the timeout.
10. etc.

**Comment by kishorenc** [comment]
@melovv 

I presume that you've already read about how you can create multiple Typesense replica servers that sync from master: https://typesense.org/0.9.2/guide/#high-availability

The replica servers asynchronously pull updates from master, so they will be eventually consistent. Currently our client libraries send reads only to the master, and they fall back to the replica only a failure/timeout. 

However, since Typesense just uses a HTTP API, you can very easily change this behavior for your own needs by directly using a HTTP client to make the searches in a round-robin fashion. See the [shell snippet](https://typesense.org/0.9.2/api/#search-collection) for making a direct HTTP search request. You just need to parameterize the host used in a `get_host()` function that returns a new host for every call, and your requests would be spread out across all replicas.
