### ISSUE TITLE
Long search time 

### ISSUE THREAD

**Issue by orasik** [typesense/typesense#575]
## Description
A query to search all documents with no filters is taking too long (more than 7 seconds).

The number of total records in the collection: 5 million.
The number of returned results for the search query: 0.5 million.
Server RAM: 16GB.
Used RAM: 8.6GB.
Running one node with version `0.23.0.rc27`

**It was running fine when there were around 4.3 million records. The issue started to appear after hitting the 5 million point.**

## Steps to reproduce

Search for a word without filters, sort by time.

## Expected Behavior
Less than 2 seconds to return results.

## Actual Behavior
more than 7 seconds.

## Metadata

**Typsense Version**: `0.23.0.rc27`

**OS**: Docker

**Comment by kishorenc** [comment]
@orasik 

Since Typesense does not pre-sort results, for stop words like `the` which occurs in a lot of documents, a large number of documents need to be processed to fetch results. 

In the future, we plan to introduce a way to fetch documents (especially these types of single word searches) in a pre-sorted fashion. For now, removing such stop words or pre-caching them with a long TTL is the work around.

**Comment by orasik** [comment]
@kishorenc I actually implement stop words to avoid this issue with stop words. 
I have identified the issue, basically, there was `*` before the word which for some reason slowed down the search.
Once I removed the asterisk, it is back to speed.
