### ISSUE TITLE
bug: searching for random regex-like expressions breaks Typesense

### ISSUE THREAD

**Issue by michaelgrigoryan25** [typesense/typesense#582]
## Description

I was visiting several of the websites provided in the documentation and wanted to test how Typesense would handle random regex-like expressions. To be more specific, I visited:

- https://books-search.typesense.org/
- https://songs-search.typesense.org/

## Steps to reproduce

1. Open DevTools and switch to the `Network` tab.
2. Visit any of the websites provided in [typesense/typesense](https://github.com/typesense/typesense) README.
3. Search for `__-420=-__1239512395@!89@!!@` or `--++323__-420=-__1239512395@!89@!!@`

## Expected Behavior

I expected that Typesense would have returned an empty response or an error related to the search syntax.

## Actual Behavior

After some more testing, it seems like both of these websites fail to respond properly. The requests timeout after 10 seconds and a response is not returned.

## Metadata

**Typsense Version**: Unknown

**OS**: Unknown

**Comment by kishorenc** [comment]
@michaelgrigoryan25 

Since underscore (`_` character) is not indexed in these collections, the query `__-420=-__1239512395@!89@!!@` gets parsed as a query beginning with the `-` character (e.g. `-420...`) and this becomes an exclusion query, i.e. "get all documents that does not contain this word" type of query. 

This means that Typesense now has to rank all the documents which could be millions, so that can take some time in large collections, like the books and songs datasets. We've an item on our backlog to fallback to natural ordering of documents in such cases to prevent high latency.

**Comment by michaelgrigoryan25** [comment]
Yes, but the request timeouts without sending a valid response which can cause issues on others' implementations. 

Maybe sending a `204` instead, or something similar would be more appropriate instead of cancelling the request.

**Comment by kishorenc** [comment]
The request is not cancelled by the Typesense server, but the JS client which has been configured with a short timeout. Given sufficiently large client side timeout, the Typesense server will return a valid response. Ofc, that could take some time, so to protect against that, Typesense also allows you to send a `search_cutoff_ms` parameter which will ensure that an early "return" is made if a request just takes too long.

**Comment by michaelgrigoryan25** [comment]
Ah, makes sense. Thanks for elaborating.
