### ISSUE TITLE
Filtering on a facet in combination with using the search bar is not always giving the correct total results fond.

### ISSUE THREAD

**Issue by Geoffry304** [typesense/typesense#587]
## Description

Filtering on a facet in combination with using the search bar is not always giving the correct total results fond.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/3656871/165923407-e363146f-1d08-4c3a-91bc-90fb90b4f712.png)
![image](https://user-images.githubusercontent.com/3656871/165923538-36fdb1c9-a14e-4f86-b280-e24c8e5caa01.png)

When filtering more down for example selecting a company then the result is correct.

## Expected Behavior

The results should be equal as the result off the active filter

## Actual Behavior

The resulst is not equal as the active filter.

## Metadata

**Typsense Version**: 0.22.2

**OS**: CentOS 8

**Comment by kishorenc** [comment]
@Geoffry304 

Let me explain what's happening here and suggest a way to fix those counts.

When there are many words that could match a given prefix (like `dom`) in this example, Typesense by default only considers the first 4 relevant words in the dataset. This is because for shorter prefixes like `e` there could be thousands of words that could match that prefix and without more information, it's difficult to guess which word the user is attempting to type and going through all possible words will be expensive.

The actual `K` prefix-expanded words that are considered by Typesense could vary between the "filtered" count query and the "unfiltered" total count query. And this case leads to the difference in the document counts (since both queries could pick a different set of `K` matching words based on the filter condition used).

You can set `?exhaustive_search=true` to make Typesense consider all words matching the query so that this count issue does not happen. The performance impact of this parameter should not be a problem on small/medium datasets.

Let me know if this works.

**Comment by kishorenc** [comment]
Setting `?max_candidates: 1000` might also be sufficient here. See my comment here: https://github.com/typesense/typesense/issues/540#issuecomment-1064707861

**Comment by Geoffry304** [comment]
Hello @kishorenc thanks for the information, using exhaustive_search and max_candidates is not working, my total is staying on 36 results.

**Comment by kishorenc** [comment]
That's odd. Would you be able to give me access to the dataset? Please email me at: contact@typesense.org

**Comment by Geoffry304** [comment]
Thank you for great support.
Turns out the latest version did the trick.
