### ISSUE TITLE
[Feature Request] Cursor based pagination

### ISSUE THREAD

**Issue by bianjunjie1981** [typesense/typesense#591]
## Description

This is an inflexible practice, and in fact pagination in modern applications may not be uniform.
It is more appropriate to follow the general practice of the database and use **limit index,count**. Also, **from,to**.
That's the nature of getting data, not pagination, which covers fixed pagination behavior, which is dynamic, and pagination is just one implementation.
It becomes very simple to organize data by cursor, such as 10->20->50->100->120.

**Comment by kishorenc** [comment]
Fair point. We will add an alternative pagination option using `offset` and `limit` like SQL.

**Comment by phungleson** [comment]
Hey peeps, since where are at pagination, another common strategy is cursor-based pagination.

**One benefit of cursor-based pagination is that it works consistently even when someone mutate the dataset.**

Elasticsearch implemented it as some form of `search_after`.

https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html

But generally you can take a look at how graphql implemented cursor based pagination.

https://graphql.org/learn/pagination/

Basically, you need input: `cursor_after` to move forward or `cursor_before` to move backward.

And in the output, you need a `cursor` for each hit. So that to travel forward, user set `cursor_after` to the last cursor of previous request, and to travel backward, user set `cursor_before` to the first cursor of previous request.

**One important aspect is that cursor should be `base64` encoded, so that it doesn't matter what kind of ordering being applied.**

Hope my explanation is simple enough to evaluate the possibility of adding this to TS.

**Comment by caiorhian** [comment]
Hey everyone, we're just starting with Typesense, it's been a great experience so far.

But on the pagination area, we also lack a cursor based version of it. All of our team APIs were already working based on cursor and we would like to keep it that way based on all the benefits that it brings.

**Comment by kishorenc** [comment]
`offset` based pagination is available in this RC build: `typesense/typesense:0.25.0.rc20`

You can now send the following two parameters that correspond to their SQL equivalents:

- `offset`: Number of results to skip
- `limit`: Number of results to pick

Please give it a spin and let me know how it works! Once we verify that the API works as expected we will add support for this in instantsearch.js adaptor as well.

cc @caiorhian @bianjunjie1981 @robinsimonklein

**Comment by phungtranminh** [comment]
Hi, in the mean time, I would like to try out limit and offset feature, however, it is not available in openapi.yml yet

https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml

Not sure I am looking at correct document, do you plan to add them in?

Additionally, I guess typesense doesn't run into issues, like with traditional SQL, mentioned in the above [article](https://use-the-index-luke.com/no-offset)?

**Comment by jsutaria** [comment]
+1

**Comment by dazld** [comment]
@kishorenc are you waiting on feedback on that RC build before taking this further?

**Comment by kishorenc** [comment]
@dazld 

The `offset` and `limit` parameters are alternative to `page` and `per_page` and are already part of the `0.25.1` release. They offer more flexibility in pagination and plays nice with graphql libraries. 

However, a cursor API that provides a snapshot/frozen view of the results during pagination via something like `cursor_after` is not yet implemented.

**Comment by theovier** [comment]
@kishorenc 

> However, a cursor API that provides a snapshot/frozen view of the results during pagination via something like `cursor_after` is not yet implemented.

Does "not yet" in that context mean that it is still planned? I couldn't find anything regarding that on the roadmap.

**Comment by kishorenc** [comment]
@theovier 

It's not planned. Unlike databases where the sort order can be fixed at indexing time (based on a field value), search queries have a variable component: the text match score which is dependent on the query sent. Hence, a cursor API is far more difficult to pull off.

**Comment by theovier** [comment]
That makes sense. Thank you for swift response! ❤️
