### ISSUE TITLE
Question about speed

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#626]
Search engines tend to get slower as the number of documents increases. They also get slower as the complexity of the request increases, eg  when adding more filters/facets to the query, the response times increase exponentially.

I've seen websites that appear to have a seperate search engine for each product category, and I guess this is to keep each individual engine fast.

Imagine having a collection with 5 million documents. Will it be useful to split this into, for example, 500 collections of 10000 docs. The main purpose is to keep response time low when user selects multiple facets. I guess the answer would be yes if typesense keeps the data / index for each collection separate, thus not having to search the whole dataset. (assume that the multisearch endpoint will be used to get all facets in 1 call).

Also, if I wanted to create an autocomplete spanning all collections, would I be able to do that via federated multi-search, or would that be problematic as each collection returns results?  (A separate collection with minimal data of all docs would then still be required).

**Comment by kishorenc** [comment]
Sharding of data is inevitable as sizes grow, but 5M docs is not a terribly large number unless you are doing a lot of wildcard querying (this is something that we plan to address as well in future). You can just throw more CPUs at it and get along. I wouldn't recommend trying to shard unless you really see a need for it. 

Having said that, splitting data into individual collections will certainly help reduce the overall search size. However, `/multi_search` does not aggregate the data back into a single unified view so that must be done client side, so the idea of having a light-weight single collection would be a better approach.
