### ISSUE TITLE
Typesense High Availability and memory

### ISSUE THREAD

**Issue by thenitai** [typesense/typesense#631]
Hi there,

First off, congratulation to you all for this awesome piece of software. We want to move away from ElasticSearch. For now, we started with indexing contact data which has around 5 million records in MongoDB.

Setup:
3x Ubuntu LTS with the latest Typesense 0.23 deb.
Each server has 2CPU with each 4 cores

Collections:
750 collections with documents that only contain 5 fields (email, names, etc.).

That said, after indexing appr. 2 million records we saw that all servers kept on crashing and reloading all the data. After some searching, I saw that the system reported out of memory. Hence, we upgraded all servers to 16GB.

My question is why does Typesense crash? Shouldn't there be some kind of setting on how much memory it can consume? From a production standpoint, I see my team having to get up in the middle of the night to restart servers, allocate more memory, etc. This also begs the question, what if there is no more memory available (hardware-wise)?

We run KeyDB, MongoDB, MySQL, and several node apps, and I can't believe there is no such setting available. I'm sure, I miss something obvious? :)

**Comment by kishorenc** [comment]
@thenitai 

> My question is why does Typesense crash? 

Many operating systems kill a process that uses too much memory, especially when OS is running out of memory for critical operations. 

> Shouldn't there be some kind of setting on how much memory it can consume?
> This also begs the question, what if there is no more memory available (hardware-wise)?

The best approach here is to allocate swap memory. This will allow the Typesense process to swap to disk, which will cause degradation in performance but will not bring the service down. This is a superior approach to having hard memory limits because memory usage tends to fluctuate during high concurrency and can drop back to a safe baseline. We also cannot check the memory usage in fine granularity as the system call is relatively expensive to do frequently (multiple times per second).

So I recommend configuring swap memory and have an alert that fires when swap is used so that you can take appropriate action on a planned capacity expansion.

**Comment by thenitai** [comment]
> The best approach here is to allocate swap memory. This will allow the Typesense process to swap to disk, which will cause degradation in performance but will not bring the service down. This is a superior approach to having hard memory limits because memory usage tends to fluctuate during high concurrency and can drop back to a safe baseline. We also cannot check the memory usage in fine granularity as the system call is relatively expensive to do frequently (multiple times per second).

Thank you for your answer. Yes, we added swap space to "circumvent" our app to crash. However, I still advocate that there is some sort of memory settings for Typesense. I mean you don't need to check every second, but only allow Typesense to use a certain space. Say for 16 GB memory I can just tell Typesense to only use 12 GB.

In any case, this is just a suggestion and I'm sure you guys have a very valid reason to do certain things as they are. Thanks again for this awesome piece of software.
