### ISSUE TITLE
Do not disclose any sensitive api key material in scoped api keys

### ISSUE THREAD

**Issue by lleifermann** [typesense/typesense#643]
## Description

When generating a new scoped API key, parts of the search key (first 4 characters) will be disclosed in the in the result. I believe this has been done to identify on the server which API keys the scoped key correlates to. IMHO not a single character of the search api key should be disclosed to a client. Why not use a UUID of the key? 

Example decoded scoped key: 

`J6uxV8L7IYTO2wmv12g5TZ0qAyEchVrwQB2RFstgE20=Rwov{"filter_by":"customerId:2fc111e8-c1c9-4cf4-add7-d0644f9ecd64"}`

Observe that the characters `Rwov` are included in the scoped key which matches my search key i've given the `generateScopedSearchKey` function.

## Steps to reproduce

1. Create a search key as explained in the documentation -> https://typesense.org/docs/0.23.0/api/api-keys.html#create-an-api-key
2. Use that key in generating a new scoped api key -> https://typesense.org/docs/0.23.0/api/api-keys.html#usage
3. Base64 decode the result 

## Expected Behavior

Typesense should not disclose any character of a search key in scoped key generation, but instead use some other identifier, like a database UUID.  

## Metadata

**Typsense Version**: 23.0

**Comment by kishorenc** [comment]
@lleifermann 

We do indeed use the first few characters to reduce the search space for the parent key correlation. We chose this approach over a `uuid -> real_api_key` mapping since Typesense generates 32-char API keys and sacrificing the first few characters made no practical difference in terms of security: given the network overhead in making an API request, it's not going to be possible to "crack" the parent key via brute force. 

Are there other aspects of this issue that you are concerned about?
