### ISSUE TITLE
Disallow unsafe collection schema alterations

### ISSUE THREAD

**Issue by andreww2012** [typesense/typesense#655]
## Description

Kind of a follow-up of #648.

If you change the field type to an incompatible with a previous one in one go, the operation would succeed with dangerous consequences. But if you first drop a field, and then try to re-add it with a type incompatible with stored data (honestly, I expected removal of a dropped field would remove that field in all the documents), it would correctly fail with the following error: *Schema change is incompatible with the type of documents already stored in this collection. Existing data for field `field_name` cannot be coerced into a `<new type>`.*

## Steps to reproduce

```sh
docker volume create typesense-schema-alteration-bug

docker run -p 8112:8108 -v typesense-schema-alteration-bug:/data --name typesense-schema-alteration-bug -itd typesense/typesense:0.23.1 --data-dir /data --api-key=123

curl -L -X POST 'http://localhost:8112/collections' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "name": "locations",
    "fields": [
        {"name": "loc", "type": "geopoint"}
      ]
  }'

curl -L -X POST 'http://localhost:8112/collections/locations/documents' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "id": "a",
    "loc": [1, 2]
  }'
```

Let's patch the schema in one go - I would expect this to fail, because `geopoint` cannot be coerced into an `int32`, but it will succeed:

```sh
curl -L -X PATCH 'http://localhost:8112/collections/locations' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "fields": [
      {
        "name": "loc",
        "type": "int32"
      },
      {
        "name": "loc",
        "drop": true
      }
    ]
  }'
```

After that, one won't be able to even delete a document with a "broken" type:

```sh
curl -L -X DELETE 'http://localhost:8112/collections/locations/documents/a' \
  -H 'x-typesense-api-key: 123' \
  --data-raw ''
```

Response & logs:

```json
{
  "message": "Bad request."
}
```

```
E20220713 12:32:49.651454   309 batched_indexer.cpp:196] Exception while calling handler documents:delete
E20220713 12:32:49.651504   309 batched_indexer.cpp:197] Raw error: [json.exception.type_error.302] type must be number, but is array
```

## Expected Behavior

Disallow unsafe collection schema alterations.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Windows 10 19043.1165

**Comment by kishorenc** [comment]
@andreww2012 

Thanks, this is a good catch. It turns out that the issue only happens when you have `drop` as the second item. If you placed the `drop` clause first, it would have thrown the appropriate error message about incompatible type: 

```
curl -L -X PATCH 'http://localhost:8112/collections/locations' \
  -H 'X-TYPESENSE-API-KEY: 123' \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "fields": [     
      {
        "name": "loc",
        "drop": true
      },
     {
        "name": "loc",
        "type": "int32"
      }
    ]
  }'

```

However, I've fixed this ordering issue in `typesense/typesense:0.24.0.rc19` Docker build.

**Comment by andreww2012** [comment]
Could it also be possible to implement removal of all the data stored in a dropped field?
I faced the bug in question when I was trying to adapt the field with `geopoint` type to store `int32` and naturally I was expecting the dropped field to be *completely* removed, meaning all the documents will no longer have it. And after the operation succeeded, I started to see a lot of weird errors because the data was not dropped but rather "coerced" into `int32` which should've not happened. 😄 
I guess, at least on the user's side, this could be implemented by adding the ability to include `"drop_values": true` clause when `"drop": true` is present.

**Comment by kishorenc** [comment]
In Typesense a document can have any number of fields and the fields that are **not** part of the schema are not really "managed" by Typesense because our indices are in-memory and only fields in the schema are indexed. So a `drop` in this context means removing the in-memory index. 

I'm not sure we will support a `drop_values` action without a strong need/requirement because so far we don't have any API semantics for otherwise changing the on-disk data once it is stored. You can always exclude fields from response, and we will leave it upto the user to reindex the data if they really need the document to be devoid of that field.

**Comment by admtech** [comment]
I support the feature request of @andreww2012. We now use Typesene like a real database and not just as a search engine. With the document store we have everything we need and for some non-relevant data we save synchronizing with the main database. Of course, since adding by automatic fields is so easy (even the ones that are not indexed) a simple global deletion of these fields with their data would be desirable. 

As long as there is no "Modify" on an existing field, we of course need the possibility that the actual content is not lost when removing the index field, but an additional option like `"drop_values": true` would be really helpful and make Typesense even more usable. Keep up the good work  :-)

**Comment by kishorenc** [comment]
@admtech 

I'm going to close this issue since the primary issue was about a bad alter behavior. Can you please create another issue as a feature request for the `drop_values` action?  Thank you in advance.
