### ISSUE TITLE
Support for other data types

### ISSUE THREAD

**Issue by joshxyzhimself** [typesense/typesense#686]
## Description

Just some questions related to PostgreSQL and TypeSense data types.

## Questions

- is `geopoint` in typesense equivalent to `point` in postgresql?
- is it possible to support double (64-bit float) for better precision?
- is it possible to support for timestamp (iso / sql timestamps)? im aware they can be converted to millisecond timestamps to second timestamps for compatibility with int32 / int64 / float fields, but im curious if standard (iso / sql) date & time timestamp strings are possible.
- if timestamp ever supported, is it possible to use sorting / filtering?

**Comment by kishorenc** [comment]
1. I believe PG's `point` is meant for storing 2-D cartesian co-ordinates by Typesense geopoint is more specific: it is meant for storing only geographic co-ordinates since the operations will take into account the curvature of the earth.
2. We don't have float64 data type
3. We don't have native data/time datatype apart from int64
4. N/A because of 3

**Comment by joshxyzhimself** [comment]
Updated the title so it will show up on search results in case other people also search for it, thank you.

**Comment by skipjack** [comment]
@kishorenc any updates on supporting iso timestamps and filtering natively? I guess sorting comes free now that you guys support string sorting. Just curious if broader date support is anywhere on the roadmap...
