### ISSUE TITLE
We love Typesense, but memory bogs us down

### ISSUE THREAD

**Issue by thenitai** [typesense/typesense#705]
Hi there,

First off, we love Typesense. It helped our customers and us quite a lot and solved some of the issues we've had with ElasticSearch and other search engines. It also alleviated our MongoDB servers from going haywire :)

That said, we are constantly battling with memory. All Typesense servers (5) are up at 95% memory usage. We keep adding more memory and are now at 24 GB for each server, but it just feels like there is no end in sight. With ElasticSearch, there is at least the option to limit the RAM usage, but I don't see an option with Typesense.

In the past, the Typesense servers just crashed, and we have since added Swap space to prevent that. However, this architecture implies that Typesense just takes what it can get, no matter what, i.e., don't care about system stability.

Is that the case? How are we supposed to resolve this? Is there no option to limit the RAM usage of Typesense?

**Comment by jasonbosco** [comment]
@thenitai Thank you for the kind words!

Unlike Elasticsearch, Typesense is an in-memory search engine - the entire index is stored in memory for performance. If X is the size of your dataset, you need [at least 2x - 3x amount of RAM](https://typesense.org/docs/guide/system-requirements.html#choosing-ram) to hold the index in memory. So as X keeps increasing, RAM requirements will also keep increasing - this is by design. 

Configuring swap is only a safety mechanism to prevent the operating system's OOM reaper from killing the Typesense process when it is out of memory. So as soon as swap is used, you do want to add more RAM. 

Given that the RAM consumption model is by design, there's no way to restrict Typesense's RAM usage, except by managing the size of your dataset and indexed fields.

**Comment by thenitai** [comment]
Thanks for the quick reply.

I understand the architecture, and maybe we go about deploying Typesense wrong then. So, in our case, we have millions of contacts indexed for each tenant (multi-tenant system) created a collection.

Now that we are leveraging Typesense for other data, would you recommend adding a dedicated Typesense server for other data? For example, server 1 (and clusters) hold an index for contacts, and server 2 (and cluster) holds an index for emails, etc.?

I'm just looking for some guidance here as we want to use Typesense for other data, but I fear we will be running into memory issues and then need to run 5 servers, each with 192 GB of memory. As we host at one point, there is no other memory option anymore.

Thank you.

**Comment by jasonbosco** [comment]
> Now that we are leveraging Typesense for other data, would you recommend adding a dedicated Typesense server for other data? For example, server 1 (and clusters) hold an index for contacts, and server 2 (and cluster) holds an index for emails, etc.?

Yeah, given your scale and particular use-case, I'd recommend creating different clusters for each search experience. This way, you can also scale each cluster independently of each other and avoid having to provision more CPU than needed. For eg, may be contact search only requires X amount of CPU cores to handle the traffic, but email content search might require Y amount of CPU cores. 

You're also effectively sharding the data across multiple clusters, which helps you potentially not hit limits with max RAM available at your hosting provider. If you do hit this limit, you can then further shard by customer ID potentially (eg: place all customers who have IDs in range [1-99999] in Cluster A,[100000-199999] in Cluster B, etc.

That said, the total amount of RAM needed to index a particular dataset of size X is not going to go down even if you split it across multiple Typesense clusters. You still need 2x-3x RAM to hold the entire dataset in memory, whether that's on a single cluster or multiple clusters.
