### ISSUE TITLE
Embedding search parameters in scoped API keys when using federated search.

### ISSUE THREAD

**Issue by andycansdale** [typesense/typesense#747]
## Description

I'm having trouble locating documentation or examples regarding the use of include_fields and exclude_fields when creating a scoped API key for federated searches. The collections have different schemas and I need to either whitelist or blacklist fields on a collection by collection basis. I can only find examples for non-federated searches.

Also, the [results parameters docs](https://typesense.org/docs/0.23.1/api/search.html#results-parameters) explicitly mentions the use of exclude_fields in API keys, but include_keys does not, leading me to wonder if perhaps it's not an option when creating scoped API keys.

## Steps to reproduce

As a test, I created a new API key using an existing documents:search API key on the command line, adding the collection name before the field with dot notation (collection.field), but the field still appears

```
KEY_WITH_SEARCH_PERMISSIONS="xxxxxxxxxxxxxxxxxxxxxxxxxx"
EMBEDDED_SEARCH_PARAMETERS_JSON='{"exclude_fields":"locations.type"}'

digest=$(echo -n $EMBEDDED_SEARCH_PARAMETERS_JSON | openssl dgst -sha256 -hmac $KEY_WITH_SEARCH_PERMISSIONS -binary | base64)

scoped_api_key=$(echo -n "${digest}${KEY_WITH_SEARCH_PERMISSIONS:0:4}${EMBEDDED_SEARCH_PARAMETERS_JSON}" | base64)

echo $scoped_api_key
```

## Expected Behavior

Ideally I would like to use include_fields for three collections in a single scoped API key for use on our public website. This would allow us to then add private fields to the collection and reuse the same collection with a different API key in our admin, but with access to the private data.

## Actual Behavior

The key is accepted and a response is received, but the initial test using exclude_fields and collection.field notation still shows the field in the response.

## Metadata

**Typsense Version**: 0.23.1

**OS**: Typesense Cloud

**Comment by jasonbosco** [comment]
@andycansdale You can indeed embed `include_fields` (or any search parameter) in a scoped API Key. The reason we mentioned `exclude_fields` explicitly in the docs is because we figured that would be the more common use-case to exclude select sensitive fields from the results. We wanted to call out that, to enforce exclude_fields (so users can't change it) it should be set in a scoped api key.

To answer your question of how to use scoped api keys with multi_search, as of v0.23.1 Typesense now supports the ability to specify a parameter called `x-typesense-api-key` within each search in a multi search request. 

So you want to generate one scoped api key per collection with the filters for just that collection embedded, and use separate api keys. 

If there is an `x-typesense-api-key` specified at the search level, that takes precedence over the one specified in the API Call header / query param. 

This is documented under this table: https://typesense.org/docs/0.23.1/api/federated-multi-search.html#multi-search-parameters
