### ISSUE TITLE
Typesense cloud doc link broken (404)

### ISSUE THREAD

**Issue by loic-hamdi** [typesense/typesense#749]
In Typesense cloud, collection search:

<img width="723" alt="Screen Shot 2022-10-08 at 10 24 59 AM" src="https://user-images.githubusercontent.com/3080026/194715011-00c918af-10a4-4e95-a24d-9f6b6d084446.png">

`Docs` link goes to : `https://typesense.org/docs/0.23.0.rc69/api/documents.html?&_ga=2.20212024.126681334.1665242601-11888179.1661195689#search-parameters`

Which lead to Error 404 page

**Comment by jasonbosco** [comment]
It looks like your cluster is running an RC build. We currently don't publish docs for any RC builds - we only publish docs for the GA versions, which is why those links are showing a 404. 

The links should work again, once you upgrade to the latest GA version for v0.23.1 which I'd highly recommend.
