### ISSUE TITLE
Question about facet

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense#805]
Firstly I want to say Thank u Typesense team
Question:
Instantsearchjs requires facet for range filter
E.g: filter from date to date
I want to know what is different between index facet and without facet? Which one will use more memory, more CPU…? Disadvantages?

**Comment by huynv86** [comment]
Almost dates are timestamp and they are unique

**Comment by jasonbosco** [comment]
Faceting will indeed consume more memory comparatively, especially if it has all unique values for the field. I would recommend first indexing your dataset as is with faceting turned on for the unix timestamp field and then again with faceting turned off, compare memory usage and then if you want to optimize it, you could reduce the granularity of the date field, for eg by "rounding down" timestamps to the start of the day, this way there are less unique values. 

Separately, facet computation also consumes more CPU than non facet queries. I would recommend benchmarking to determine the exact impact. 

But if you're using Instantsearch, unfortunately there's no way to use a non faceted field in a filter widget, since that's an Algolia quirk.

**Comment by huynv86** [comment]
Thank u for your quick reply
