### ISSUE TITLE
"Upsert" Issue when updating collection by batch

### ISSUE THREAD

**Issue by ncailleux** [typesense/typesense#809]
## Description

i think I just spot an issue when updating batch of documents in a collection with `upsert` action.
I updated to 0.23.1 a few days ago and I just saw that documents wasn't updated at all after my script to update my documents just ran well.

This was my call, where `to_index` is an array of documents:
`
client_.collections[info_index['name']].documents.import_(to_index, {'action': 'upsert'})
`

After seeing that my scripts wasn't working, I search in typesense docs again. I saw the new `emplace` action in the docs. I changed the action and it's working again:
`
client_.collections[info_index['name']].documents.import_(to_index, {'action': 'emplace'})
`
### Conclusion

So my issue is fixed, but if it's a real issue, I just want to report it, I didn't see any issue about it.
Upsert action don't update documents as expected.

## Metadata

**Typesense Version**: 0.23.1
**Typesense Python package version**: 0.14.0
**OS**: Linux/UNIX (EC2 t3)

**Comment by kishorenc** [comment]
@ncailleux 

What version of Typesense where you using before upgrading?

**Comment by ncailleux** [comment]
The version just before, 0.23.0

**Comment by kishorenc** [comment]
@ncailleux 

Are you able to try with `upsert` again to see what error you are getting in the API response? The `upsert` requires the full document (so can't have missing fields), while `emplace` tolerates sending either full/partial documents. I wonder if there was a bug earlier which wasn't enforcing this constraint. In any case, it would be good to see what the error message now so that we can rule out other issues.
