### ISSUE TITLE
Best Matched item doesn't get sorted

### ISSUE THREAD

**Issue by jd-0001** [typesense/typesense#81]
Hello,
Is this normal behaviour to keep best matched item on top and sort others.
If I search for perticular item and apply sorting, item with perfect match always stays on top no matter whichever sort I apply.

## Steps to reproduce

Type for any query which you set upon with specific string.

## Expected Behavior

I think if I query and sort it should sort all queried items including best matched items or some kind of flag where I can enable sorting of all items including best match.

## Actual Behavior

It isn't sorting best matched items.

**Typsense Version**: 0.12.0

**OS**: Ubuntu

## Other

I have sent you typeSense data if you like to check it out:
Follow below query for re-production:
* search 'vuexy'
* apply sort-by price (DESC) [item_price:desc]
* apply sort-by price (ASC) [item_price:asc]

**Comment by kishorenc** [comment]
@jd-0001 String similarity is the primary metric used for sorting results. The sort-by fields are used for tie breaking when multiple documents share the same string similarity score. We describe the [ranking and relevance here](https://typesense.org/docs/0.11.0/guide/#ranking-relevance).

This is because Typesense is primarily a text search engine that's supposed to return results that match your query closely. If we did not do that, we could have a case where a particular item whose string NOT matching your target query showing up at the top just because it has greater score. 

For e.g. let's say someone is searching for "iphone" and there happens to be another product called "xiphone" which is priced higher than an iPhone -- it would end up showing above "iphone" if we strictly ordered results based on sort-by fields without giving important to query string matching.

**Comment by jd-0001** [comment]
Yeah @kishorenc you are right. If we consider your example is it possible to make 'xiphone' show up according to it's price.
According to my knowledge current situation is something like, sorting is performed by "best match" and "price" both.
So, can I make 'iphonex' appear above according to it's price.

Thanks ~

**Comment by kishorenc** [comment]
>  sorting is performed by "best match" and "price" both.

Yes, sorting is performed first on string similarity and then only on specified sort-by fields. This order cannot be changed. While it looks like a useful thing to have, from experience this does not work well for a lot of cases: sorting by price makes sense only on items that are relevant to your search query. Otherwise, the results will look terrible for a lot of other general search queries.

**Comment by jd-0001** [comment]
Thanks @kishorenc for your time :)

**Comment by kishorenc** [comment]
@jd-0001 Please see the updated ranking and relevance section in the latest 0.12.0 release:

https://typesense.org/docs/0.12.0/guide/#ranking-relevance

It gives you more flexibility in terms of having absolute control over the sort order.
