### ISSUE TITLE
Show offset and length of highlighted text

### ISSUE THREAD

**Issue by markerpen** [typesense/typesense#83]
I'm looking to get the various offsets and lengths of highlighted text. 

For example, the string 'The **quick** brown **fox**' could include the following:

```
[{
  "text": "quick"
  "offset": 4,
  "length": 5
}, {
  "text": "fox",
  "offset": 16,
  "length": 3
}]
```

Parsing which words are within `<mark>` tags can be tricky, especially when dealing with multi-byte Unicode characters. If the search response included explicit string offsets and lengths, highlighting would be much more useful.

**Comment by kishorenc** [comment]
@markerpen Can you please explain how you intend to use the offsets and lengths? I would like to understand your use case better.

**Comment by markerpen** [comment]
Sorry for not replying sooner - my use case is for searching documents within a smartphone app. The app would make an API call to the server, the middleware layer would query Typesense and send the JSON back to the app. Using explicit highlight ranges make it easier - for example, iOS has NSAttributedString which takes in one or more ranges in which to highlight a block of text.

At the moment, the middleware has to extract the offset and length from the HTML string from Typesense - extracting the string within the <em> tags and turning those into explicit offset-length pairs.

**Comment by manavo** [comment]
Just to put another use case here into context (as I've just ran into this): to highlight the matches in the field's original value (not just showing the snippet).

To do this now, you'd need to work out where the snippet is in the field's original value value, and then insert the `<mark>` tags (or whatever other highlighting needs doing).

I guess you could strip the tags, find the original text that matches, then replace that with the marked up snippet, but I'd feel more confident if I had the offsets and lengths to then apply the highlighting myself if needs be.

Thanks for considering this! 🙂

**Comment by jasonbosco** [comment]
@manavo For your particular use case, you can use the `highlight_full_fields` query parameter when searching. You'll then receive the full value of the field with highlights in addition to the snippet. Does that work?

**Comment by manavo** [comment]
Yes and no, as it complicates things with escaped HTML etc in this specific use case. 

Also, I noticed that the snippet at the moment ends up varying slightly sometimes from the original text, it changes double spaces to a single space, so you can’t directly match the snippet text. 

As a different possible issue, what happens if the text itself contains a `<mark>` element?

**Comment by manavo** [comment]
Thanks for the quick reply @jasonbosco !

Yes and no, as it complicates things with escaped HTML etc in this specific use case. 

Also, I noticed that the snippet at the moment ends up varying slightly sometimes from the original text, it changes double spaces to a single space, so you can’t directly match the snippet text. 

As a different possible issue, what happens if the text itself contains a `<mark>` element?

**Comment by manavo** [comment]
Just another little update for this (reason why the indexes would be useful).

With #95/#122 at the moment, some extra tokenization is required to pre-process the data. The specific use case for me was email addresses and needing them to be partially searchable.

But that means the data that Typesense returns for me doesn't exactly match as I'd expect it, since it differs from the actual original data.

Since the pre-processing is replacing each character with a space, the string offsets themselves won't change, but matching it as a string is much harder!

**Comment by kishorenc** [comment]
Thanks for the follow up on this issue. We've certainly faced some of these issues ourselves when building out some demos, so looking into this in more detail now.

**Comment by kishorenc** [comment]
@manavo I had a question about this:

> the snippet at the moment ends up varying slightly sometimes from the original text, it changes double spaces to a single space, so you can’t directly match the snippet text.

Apart from collapsing multiple spaces to a single space, there should not be any other changes in the snippet. Have you noticed anything else?

**Comment by manavo** [comment]
Haven’t noticed anything else since that 👍

**Comment by kishorenc** [comment]
`v0.17.0` is just out and as part of that, the highlight response structure now returns a `matched_tokens` key. See the updated sample response here: https://typesense.org/docs/0.17.0/api.html#search-collection

To find the actual offset, you can do a find on the actual text. I went with returning the actual matched tokens and ensuring that the snippet text is verbatim (earlier spaces were getting squashed) instead of returning offsets, since that introduced some ambiguity with multi-byte (non-ASCII) character sequences. Some languages treat unicode text as byte strings, while others treat them as symbols, so an index/offset will be confusing.

> As a different possible issue, what happens if the text itself contains a <mark> element?

You can also now customize the highlighting tag used via `highlight_start_tag` and `highlight_start_tag`. Default is `<mark>` and `</mark>` respectively.

**Comment by manavo** [comment]
Sounds like an excellent solution! Will test it out ASAP 👍
