### ISSUE TITLE
Upgrade Instructions 0.23.1 => 0.24.0

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#869]
## Just wanted to check

I've had a single instance VM that's been running typesense v0.23.1 since last summer. Is it safe to kill the typesense-server process, swap in the new  v0.24.0 binary and just run it with the same config?

I'll make a full JSONL backup first as loss of our ~2million + records would be tragic. Just wanted to get an idea if there's any additional steps I should take for this upgrade?

**Typesense Version**:
0.23.1

**OS**:
Arch Linux

---
EDIT: Banger update guys, lots of stuff we can use right away (vector similarity and upgraded filter options). 💝 Awesome stuff!!!

**Comment by jasonbosco** [comment]
That's great to hear!

1. You want to stop the Typesense process via systemd (or the process manager you're using), instead of doing an abrupt kill
2. Before stopping Typesense though, I'd recommend taking a [snapshot](https://typesense.org/docs/0.24.0/api/cluster-operations.html#create-snapshot-for-backups)

Then replacing the binary and restarting should be fine.

**Comment by Bug-Reaper** [comment]
Appreciate the info @jasonbosco !

Ran the typesense server via `nohup ./typesense-server --config typesense.ini &` so I'll have to send the process some type of interrupt. Will try to do the most respectful one.

Also gonna take a snapshot before I go for the upgrade. That's a good feature to know about :+1:
