### ISSUE TITLE
Feature request: Treat plurals as the same word

### ISSUE THREAD

**Issue by anthonycook** [typesense/typesense#884]
## Description

Typesense should match plural words to the non-plural version by default, currently you have to handle plurals using synonyms. This is difficult to maintain on larger datasets, for example I have a large e-commerce dataset and when new product ranges are created I have to remember to setup synonyms for them, for example “phone” and “phones”.

## Steps to reproduce

Not applicable

## Expected Behavior

Not applicable

## Actual Behavior

Not applicable

## Metadata

Not applicable

**Comment by jasonbosco** [comment]
While Typesense does not yet have a rules-based approach to "lemmatization", users have been able to rely on the default typo-tolerance behavior to get plural and singular forms in the results. 

So for eg, searching for "car" or "cars" will already return results for both because the words are within 1 edit distance between each other. This works when plurals are also 2 edit distances between each other (eg: goose and geese).

For non-standard plurals like "mouse" > "mice", users typically add these as synonyms. 

Now, as of 0.24, typo tolerance only kicks-in when one or less results are found for a search term (configurable via `typo_tokens_threshold`). 

So if you set `typo_tokens_threshold` to a high number like say `10000`, you should be able to match plurals and singular.

**Comment by dropsonic** [comment]
@jasonbosco is there any plan to properly support plurals/declensions [like Algolia does](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/how-to/customize-plurals-and-other-declensions/)?

Increasing `typo_tokens_threshold` changes the behavior besides the plural form.

For example, if I search for `cat`, I expect to see the results for `cat` or `cats` only (or no results at all). 
If there are no matches for `cat` and `typo_tokens_threshold` has been increased, the system will try to handle it as a typo and return the results for `car` because it is only 1 editing between `cat` and `car`. From the user's standpoint, that is completely unexpected.

Besides the plural form in English, it is crucial for searching by declensions in non-English languages (e.g., in German `hemd`, `hemde`, `hemds`, `hemden`, and `hemdes` should be treated as the same work).

**Comment by alainrussell** [comment]
We're seeing the same in some of our Ecommerce data sets so +1 (to get updates)

**Comment by grantfuhr** [comment]
Also seeing the same. We have synonyms for the most searched things in our ecommerce data set, but its not exhaustive.

**Comment by jasonbosco** [comment]
As v26.0, Typesense now supports stemming, which can handle plurals, different word forms, etc: https://typesense.org/docs/26.0/api/collections.html#field-parameters

You want to set `stem: true` in the field definition.

**Comment by pavlov80** [comment]
The integrated stemming support is very weak. It can't handle simple words like:
sandals = sandal
curtains = curtain

**Comment by tharropoulos** [comment]
@pavlov80 I just ran a test to diff curtains -> curtain and sandals -> sandal and it stemmed correctly. Are you sure this isn't a synonym that affects behavior?

**Comment by tharropoulos** [comment]
Also, as of v28.0 onward, Typesense supports custom stemming dictionaries in place of Snowball stemmer's algorithmic approach: https://typesense.org/docs/30.2/api/stemming.html#basic-stemming

**Comment by pavlov80** [comment]
I think I found the issue. 
The position of the "query_by" parameter array is very important. I need to move my stem field to the beginning in order for it to work.
Alternatively, we could use "query_by_weights" and give the stem field more weight.
The difference in results between the first and third positions is 1,337 and 3, respectively.
