### ISSUE TITLE
String Sorting and Pagination

### ISSUE THREAD

**Issue by cboothe** [typesense/typesense#90]
Description

I was just reading issue #73 about sorting strings and this seems to be problematic.  Both in terms of retrieving all available results as well as formatting of the final search result. In the case of autocomplete it is also important to return results in alphabetical order ASC/DESC.

Based on your hard limit of 500 results it does not seem to me to be a performance issue to allow for a sort field on the final 500 search result set. 

The use case I am trying to solve for is a product catalog where the default sort would be on product title. How would I search for a string like 'abc%' sorted by title and then page through the results. Returning 500 records at a time without the support for sorting at the time of search. In other database systems I have seen examples of the search stopping as soon as the limit has been reached. But you would need to support some sort of offset to start the query from.

**Comment by kishorenc** [comment]
> it does not seem to me to be a performance issue to allow for a sort field on the final 500 search result set.

Sorting on a given string field within the 500 results is doable, but issue https://github.com/typesense/typesense/issues/73 was about allowing a string field like `title` to be used in the `sort_by` clause and that's really resource intensive.

Let's take a query like `phone` on a `title` field. On a large dataset, this can potentially match hundreds of thousands of documents. To sort all of these matching documents on their `title` will be very slow, compared to a numerical attribute (which is what Typesense supports at the moment). 

> The use case I am trying to solve for is a product catalog where the default sort would be on product title. 

I'm sure you would have done your due diligence here, but can you please explain to me why you would want your results to be ordered by title rather than by some popularity metric (ratings, views etc.)? 

Even in the case of autocomplete, you would generally want to show "popular" items first and not by alphabetical order. For example, when searching by country, when someone types "U", you would likely want to show `USA` rather than less popular options tailored to your demography (for e.g. I would imagine someone expecting to see `Uzbekistan` would be rare for a company with US customers).

I'm not saying that there is no valid use case for supporting sorting by strings -- but it's just that it mostly does not make sense for a search engine and so Typesense does not support it. Unlike a database where the design considerations are different.

**Comment by cboothe** [comment]
Makes sense Kishore. Ideally if we could control how the final result is presented that might be ideal. Rank by Title as well as (ratings, views) which I plan to do as well.

The issue is more with exact match and searching on SKU or model number.

So an example search query (or autocomplete) of "1640-161-9" would match

1640-161-90
1640-161-91
1640-161-92
1640-161-93

This makes sense to sort instead of having a random ordering.

**Comment by cboothe** [comment]
Perhaps what I am looking for is instead called "searchable attributes"
https://www.algolia.com/doc/guides/managing-results/must-do/searchable-attributes/how-to/configuring-searchable-attributes-the-right-way/#searchable-attributes-with-different-priorities

Where you prioritize fields.

SKU
Model Number
Title

**Comment by kishorenc** [comment]
> Perhaps what I am looking for is instead called "searchable attributes"

Typesense also gives importance to the the order of fields in the `query_by` clause. Quoting from the [docs](https://typesense.org/docs/0.11.2/api/#search-collection):

_The order of the fields is important: a record that matches on a field earlier in the list is considered more relevant than a record matched on a field later in the list. So, in the example above, documents that match on the company_name field are ranked above documents matched on the country field._

> This makes sense to sort instead of having a random ordering.

I agree with your assertion here, though. I will be happy to add a feature request for ordering the final results on a given string field to make the results look pretty. But to be honest, this can be done on the client side as well. Since Typesense limits all results to top 500 results, it should be easy to do that client side without any perf issues.

**Comment by Patrick8639** [comment]
> I agree with your assertion here, though. I will be happy to add a feature request for ordering the final results on a given string field to make the results look pretty. But to be honest, this can be done on the client side as well. Since Typesense limits all results to top 500 results, it should be easy to do that client side without any perf issues.

Excepted when we need to paginate by 25 results, for example: we need to get the 500 results and sorts them before taking only 25 results out of them...

In addition sorting on the client is not faster than sorting on TypeSense.

**Comment by kishorenc** [comment]
Preview build for string sorting is now available. Please see this comment on the issue that we're using to track this feature: https://github.com/typesense/typesense/issues/117#issuecomment-1000857228
