### ISSUE TITLE
Advice Request: Better understand the implications of facet-ed fields

### ISSUE THREAD

**Issue by Bug-Reaper** [typesense/typesense#901]
## Description

We have a collection with ~2.5 million docs and each document is associated with a primary asset file (image/video/audio/etc...).

We want to create a new field on the collection to hold the md5 hash of each document's primary asset (md5hash is 128 bits). 

It'd be very practical to be able to use `group_by` on the new `md5hash` field in order to limit the number of documents with an identical primary asset in our query responses. 

In order to use `group_by`, I see the new `md5hash` field must be a facet. I'd like to understand if this is an alright approach pursue. On one hand the field would hold fairly small (128bits encoded as a string). On the other hand we'd have well over a million or two potential values for the facet-ed field. 

We have a couple other facet-ed fields and I'm 99% sure this would be fine if we only had ~50 potential values for the field.

## Question

Wanted to get an idea if memory foot-print from facet-ed fields is adversely affected by a large number of different potential values? Or are facet fields somewhat agnostic to the number of potential different values?

**Typesense Version**:
0.24.0

**OS**:
Arch Linux

**Comment by kishorenc** [comment]
Typesense already uses hashing for storing faceted fields so the absolute length of string will not matter for facet index. 

However, since there is no way to have a field as facet-only (i.e. cannot be searched upon), we will also store it in our search index -- that would incur more memory compared to a shorter hash string. But hash strings will be random so if your asset strings already share a common prefix (e.g. `example.com/foo/X.jpg` where X is the only thing that changes across assets), they will compress better on the search index since we use a trie which compresses string prefixes well.

For `group_by` -- doing grouping on large result sets will incur appropriate additional memory usage. Actual number depends on shape of data. So no-brainer for searches, but for things like grouping the entire data set etc. you have to be aware of memory incurred.

**Comment by Bug-Reaper** [comment]
Interesting. Kinda figured string length is not a major concern here as MD5 hashes are smaller than even SHA1.

Filepaths per each document are always unique in our case and subsequently not suitable to determine if different documents share an identical file.

---

Our primary use case would be `group_by` in search (~25 results per page).

Our original concern was more that millions of different potential values for a facet-field would create many different "groups" underneath the hood and cause massive memory usage while the database was at rest. After your explanation I get the sense this is not necessarily the case?

**Comment by kishorenc** [comment]
Since the facet string is also indexed as regular search field, there will be memory usage there which is going to be wasteful. The facet index itself is not affected and won't cause any performance issues.

**Comment by Bug-Reaper** [comment]
Yea we expected there would be some unavoidable wasted memory on the indexing and that's an acceptable trade-off for us :slightly_smiling_face: .

You mentioned `group_by` as a no-brainer for searches. Is that true even if the search has large `out_of` number and a relatively small `page_size`?
