### ISSUE TITLE
Search inline of a word results zero

### ISSUE THREAD

**Issue by Bjoern3003** [typesense/typesense#997]
Hi there, I am trying to implement typesense in a ecommerce system.

Looking very nice and fast.

I am trying to describe my problem:

We have products, called "Fußballtrikot mit eigenem Logo Grün L Herren"

If I only search for "trikot", the Result is 0.
![1683186564](https://user-images.githubusercontent.com/13675579/236142538-52ad8262-c7eb-4b0f-a134-816af523da86.png)

Other Inputs working well.
![1683186541](https://user-images.githubusercontent.com/13675579/236142563-3a59531f-45dd-4664-bad2-bfb597be3620.png)

Is there any setting for collection or a placeholder in the query for that?

Thank you

**Comment by kishorenc** [comment]
Hi @Bjoern3003 

By default Typesense only does prefix searches. What you want here is an infix search, where you want the query token to match even if it is at the middle or end of the word. To do that, you have to enabled the `infix` property for the field during collection creation like this:

```
curl -k "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \             
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '{
        "name": "docs",
        "fields": [
          {
            "infix": true,
             "name": "title",
             "type": "string"
        }]
      }
```

You also need to send a `infix` parameter during searching. 

```
curl -H "X-TYPESENSE-API-KEY: abcd" "http://localhost:8108/collections/docs/documents/search?q=126&query_by=title&infix=fallback"
```

However, note that `infix` index can consume a lot of memory and is also slow because there is no way to efficiently index and search on infixes/suffixes.

**Comment by Bjoern3003** [comment]
Thank you for that. Its working well :-)
